### ISSUE TITLE
[RFC] 调试功能, task调用逻辑拆分的定义

### ISSUE THREAD

**Issue by neko-para** [MaaXYZ/MaaFramework#151]
目前[maa-support](https://github.com/neko-para/maa-support)插件基于针对全部task进行focus, 然后在回调中中断实现了简单的单步调试功能, 但是目前只能记忆当前的task, 无法维护task间的调用关系, 以及具体识别后如何进行的跳转.

---

### 目前设想的task切片和调用逻辑

待定

能否将不同行为局限到每一个特定task中? 明确边界

#### 反射task数据

目前的task数据只能通过手动扫描资源来分析, 无法处理diff进去的情况. 如果能够提供一个查询当前task数据的接口会比较方便和准确.

> 优先级较低, 目前插件内只能主动创建实例并执行调试, 而不能attach到已有实例上, 因此diff进入的内容是已知的, 理论上可以计算出来.

**Comment by MistEO** [comment]
我打算单独增加一个回调消息，通过 Option 打开，包括准备准备识别XXX、命中XXX、准备执行XXX、执行完成XXX，等等

**Comment by neko-para** [comment]
准备识别xxx应该划分到xxx里面还是它的父task里面呢?
目前感觉比较明确的逻辑是划分到xxx, 类似如下栈帧
A
A - B1
A - B2
A - B3 (命中, sub)
A - B3 - C1
...
A - B3 - C2 - ... (执行完成)
A - B1

**Comment by neko-para** [comment]
但这样的话说是栈帧, 实际上其实是线性替换的task, 当执行到B3的时候还记得A, 执行到C2的时候B3已经没有了
就, 这里是二维的stack, 感觉实际调试的时候好像更关注sub里面的?
