### ISSUE TITLE
[Feature request] 添加 MaaToolkitGetWindowWin32ControllerType

### ISSUE THREAD

**Issue by moomiji** [MaaXYZ/MaaFramework#169]
|  新 api | 对应api |
| :----: | :----: |
| MaaToolkitGetWindowWin32ControllerType | MaaToolkitGetDeviceAdbControllerType |

**Comment by MistEO** [comment]
这个逻辑不太一样，ADB 那边是模拟器决定了用什么操作类型，而集成方是不关心模拟器的，且模拟器一共就那么些种，MAA 可以覆盖，所以由 MAA 推荐一个类型。

Win32 是应用程序决定了用什么操作类型，而这正是集成方需要关心的，且 MAA 没法覆盖所有的待测应用给一个推荐类型，所以没法弄。
