### ISSUE TITLE
osx-x64 下 libMaaToolkit.dylib 缺少依赖？

### ISSUE THREAD

**Issue by moomiji** [MaaXYZ/MaaFramework#174]
版本 1.6.4
```
dlopen(/Users/runner/work/MaaFramework.Binding.CSharp/MaaFramework.Binding.CSharp/src/MaaFramework.Binding.UnitTests/bin/Debug/net7.0/runtimes/osx-x64/native/libMaaToolkit.dylib, 0x0001): Symbol not found: (__ZNSt3__18to_charsEPcS0_d)
  Referenced from: '/Users/runner/work/MaaFramework.Binding.CSharp/MaaFramework.Binding.CSharp/src/MaaFramework.Binding.UnitTests/bin/Debug/net7.0/runtimes/osx-x64/native/libMaaToolkit.dylib'
  Expected in: '/usr/lib/libc++.1.dylib'
```

https://github.com/MaaXYZ/MaaFramework.Binding.CSharp/actions/runs/8237836036/job/22527431237#step:7:3174

**Comment by moomiji** [comment]
经测试 `brew install cmake ninja llvm` 安装后也报错失败

https://github.com/MaaXYZ/MaaFramework.Binding.CSharp/actions/runs/8238206491/job/22528589265#step:5:1

**Comment by MistEO** [comment]
看不懂，我这能跑啊.jpg https://github.com/MaaXYZ/MaaFramework/actions/runs/8230657324/job/22504358486

换 macos-13 试试，macos-latest 是 12

**Comment by moomiji** [comment]
确实是 macos-12 跑不起来
