### ISSUE TITLE
`debug` `config` 目录的父目录应使用主程序所在目录

### ISSUE THREAD

**Issue by moomiji** [MaaXYZ/MaaFramework#176]
#148 玛丽怎么改了.jpg

需要考虑库文件和主程序分开的情况

**Comment by moomiji** [comment]
相关 https://github.com/MaaXYZ/MaaFramework.Binding.CSharp/actions/runs/8251891368/artifacts/1319230277

**Comment by MistEO** [comment]
那肯定不行，python 都跑到安装目录去了（

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/issues/175 准备重构一下改成自己设置目录
