### ISSUE TITLE
[RFC] 版本号定义

### ISSUE THREAD

**Issue by moomiji** [MaaXYZ/MaaFramework#208]
由于部分软件包管理器的版本号不能使用 `commit_hash`，现需一 `<unique number>` 来确定唯一版本。

---

## 目前预想新版本号定义

**Version**：`<Version Core>[-<Version Unique ID>][+<Version Metadata>]`
  - 各编号均为正整数

**Version Core**：`主版本号` . `次版本号` . `修订号` `[-(alpha|beta|rc).预发布号]` `[-post.发布后号]`
  - 主版本号、次版本号、修订号、预发布号：来自 Tags（v*）。
  - 发布后号：来自距离最近一个 Tag（v*） 发布后的 commits 次数；release 时，无该部分。

**Version Unique ID**：`(ci.持续集成号|dev.本地构建号)`
  - 持续集成号：来自 ${{ github.run_id }}，为唯一编号；仅在 CI 中有该部分，release 时，无该部分。
  - 本地构建号：建议使用 Unix 时间戳；在 CI 中无该部分。

**Version Metadata**: `[${other_metadata}]` . `[${commit_hash}.${date%Y%m%d}]`
  - 使用 `.` 区分各部分元数据，元数据字符只能为 `[0-9a-zA-Z]`
  - 如非必要，其他数据均写入 ${other_metadata}，而不是放在 Version Core 当中.
  - release 时，无 ${commit_hash}.${date%Y%m%d} 部分（因为可唯一确定）。

## 新 CI 版本号

- 要求
Tag 只能命名为：**v主版本号.次版本号.修订号[-(alpha|beta|rc).预发布号]**

- 定义
**主版本号.次版本号.修订号[-(alpha|beta|rc).预发布号]
[-post.发布后号-ci.${{ github.run_id }}+${commit_hash}.${date%Y%m%d}]**

## 可用正则及版本号举例
```
^((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-(alpha|beta|rc)\.([1-9]\d*))?(?:-(?:post)\.([1-9]\d*))?)(?:-((?:ci|dev)\.([1-9]\d*)))?(?:\+(([0-9a-zA-Z][0-9a-zA-Z.]*?)??(?:\.?([0-9a-zA-Z]+)\.([0-9]{8}))?))?$
```
- 支持按编号提取的语言
主要包括 ECMA Script（JavaScript）、PCRE（Perl 兼容正则表达式，比如 Perl、PHP 和 R）、Python 和 Go。
参见：https://regex101.com/r/QTkfGv/1

1. **_Version Core_**
2. 主版本号
3. 次版本号
4. 修订号
5. 测试阶段
6. 预发布号
7. 发布后号
8. **_Version Unique ID_**
9. 持续集成号 | 本地构建号
10. **_Version Metadata_**
11. other_metadata
12. commit_hash
13. date

**Comment by MistEO** [comment]
那改改（

**Comment by Aliothmoon** [comment]
抓虫，各编号应该是非负整数
