### ISSUE TITLE
新实践：PostRecognition PostAction for Inst

### ISSUE THREAD

**Issue by MistEO** [MaaXYZ/MaaFramework#212]

**Comment by neko-para** [comment]
把SyncContext的功能直接提供到Instance上?

**Comment by MistEO** [comment]
初步设想：

- PostRecognition PostAction 和 PostTask 一样，返回一个 task id，整体结构上也复用 post task 的逻辑
- 新增 task id 详情查询接口，返回该 task id 中所使用的 reco id 和 running id（但这俩玩意不是完全线性的，得考虑下结构），开发者可根据需要进一步查询 reco 和 running 详情
- 对于高级封装：python api 中将 run_task 接口返回值改为 reco + running 的查询详情的结构

**Comment by MistEO** [comment]
研究了一些 reco id + running id 的结构，结论是放弃（）

直接 running id 数组摆烂了（

**Comment by MistEO** [comment]
先糊了个能用的，之后再重构一下 PipelineTask 这块。有点耦合过深了
