### ISSUE TITLE
pipeline.schema.json 中模式依赖无效

### ISSUE THREAD

**Issue by MistEO** [MaaXYZ/MaaFramework#218]
OCR 的被当成 目标检测 的那个了（

![image](https://github.com/MaaXYZ/MaaFramework/assets/18511905/b4444899-ccc2-4421-9c5b-44d6ec431eb9)

@dongwlin 带带_(:з」∠)_

**Comment by dongwlin** [comment]
好像不止expected字段有问题，其他dependenciesSchemas里重新定义的字段也有问题，只是之前没人用没被发现`(*>﹏<*)′
