### ISSUE TITLE
对于桌面端，无论是OCR识别还是TemplateMatch识别都一直无法成功识别，而安卓端都可以成功识别，这是为啥啊？

### ISSUE THREAD

**Issue by gz-zg** [MaaXYZ/MaaFramework#225]
![image](https://github.com/MaaXYZ/MaaFramework/assets/140140818/95352647-15f6-4492-a30c-639d9c09dbe9)

**Comment by gz-zg** [comment]
#### 这个是install目录下的debug/maa.log
[maa.log](https://github.com/MaaXYZ/MaaFramework/files/15297549/maa.log)

---
#### 这个是根目录下的debug/maa.log
[maa.log](https://github.com/MaaXYZ/MaaFramework/files/15297622/maa.log)

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaDebugger

pip install maadebugger==1.1.0b2

可以看到识别可视化结果

**Comment by MistEO** [comment]
你的日志有点乱，安卓和 win32 都混在一起。其中有个日志用的是 1.7.0，可以更新一下版本试试。不行再抓个单独的 win32 失败的日志看下
