### ISSUE TITLE
使用FeatureMatch方法会导致报错

### ISSUE THREAD

**Issue by Jash1787** [MaaXYZ/MaaFramework#226]
MaaFramework版本为1.7.3，使用MaaPracticeBoilerplate模板进行测试。任务流水线代码如下所示：

```json
{
    "PatHead": {
        "recognition": "FeatureMatch",
        "template": "icon_pathead.png"
    }
}
```

在控制台会出现以下错误并退出控制台：

```
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.8.0) Error: Assertion failed (scn + 1 == m.cols) in cv::perspectiveTransform, file D:\a\MaaDeps\MaaDeps\vcpkg\buildtrees\opencv4\src\4.8.0-2bf495557d.clean\modules\core\src\matmul.dispatch.cpp, line 550
```

使用TemplateMatch和OCR则能正常运行。
[maa.log](https://github.com/MaaXYZ/MaaFramework/files/15296168/maa.log)

**Comment by MistEO** [comment]
崩溃时的模拟器画面，截张原图看一下。这个 icon_pathead.png 也发一下看看

**Comment by Jash1787** [comment]
测试结果显示，template使用的图档似乎有问题。重新制作template或使用其他人的图源就没有问题。

附件中附上有问题的icon_pathead.png，该图档是用BS5截图后用WIN10内建的Paint 3D加绿幕处理的，只在FeatureMatch时出问题。
![icon_pathead](https://github.com/MaaXYZ/MaaFramework/assets/169680627/df86202c-9506-4179-9569-7cf082033dcd)
