### ISSUE TITLE
找不到动态链接库问题

### ISSUE THREAD

**Issue by whalemjy** [MaaXYZ/MaaFramework#233]
exe文件无法运行
![{4D45E710-6883-4a45-B7BD-2519D23881B7}](https://github.com/MaaXYZ/MaaFramework/assets/102861575/7698358f-6f66-4642-ac7f-9ec834a29f12)

**Comment by MistEO** [comment]
装一下运行库

https://aka.ms/vs/17/release/vc_redist.x64.exe
