### ISSUE TITLE
使用MaaCommonAssets预转换文件进行日文和韩文OCR无法进行识别

### ISSUE THREAD

**Issue by Jash1787** [MaaXYZ/MaaFramework#238]
按照文档将configure.py中设置assets_dir / "MaaCommonAssets" / "OCR" / "ppocr_v3" / "ja_jp"或"ko_kr"并进行配置，会出现无法识别出文字的情况。改用"zh_cn"和"zh_tw"则能正常运行。

下图为Maa Debugger在日文识别的结果：
![maa_debugger_JP_result](https://github.com/MaaXYZ/MaaFramework/assets/169680627/d3b70726-4b80-4dd9-ab5e-483baacdbde7)

此为中文识别的结果：
![maa_debugger_CN_result](https://github.com/MaaXYZ/MaaFramework/assets/169680627/b41a9514-94c9-45e6-9023-6e538a3c6f6e)
[debug_JP.zip](https://github.com/MaaXYZ/MaaFramework/files/15446974/debug_JP.zip)
[debug_CN.zip](https://github.com/MaaXYZ/MaaFramework/files/15446977/debug_CN.zip)

**Comment by MistEO** [comment]
看起来是多语言的 det 模型出问题了，可以试试拿简中的 det.onnx + 日文的 rec.onnx，先凑合用用（其实区别应该不大），之后有空我再查一下 det 的问题
