### ISSUE TITLE
mumu12开启强制保活之后获取截图全是模拟器桌面

### ISSUE THREAD

**Issue by uchisl** [MaaXYZ/MaaFramework#243]
开启强制保活 install之后截图都是模拟器桌面 无法获取游戏内截图 
用maadebugger测试是正常的
关闭强制保活就正常了
![image](https://github.com/MaaXYZ/MaaFramework/assets/106339966/b81ae412-b724-4dad-98ed-7e6299228094)
![image](https://github.com/MaaXYZ/MaaFramework/assets/106339966/21d90864-bb4c-4491-b3ae-dd2e86639647)

**Comment by neko-para** [comment]
建议先不开保活，Maa那边好像有说怎么能弄，目前Framework应该是没适配的

**Comment by MistEO** [comment]
正常和不正常的log分别发一下

**Comment by NakanoSanku** [comment]
开启保活后，每个应用有单独的虚拟屏幕，而默认截图方案都会从id为0的虚拟屏幕截取图片，只能等后续更新所有方案都可选屏幕ID才能解决
