### ISSUE TITLE
Release v2.0 的一些想法

### ISSUE THREAD

**Issue by MistEO** [MaaXYZ/MaaFramework#248]
- [x] 移除 `is_sub` 字段，新增中断处理字段。例：next: [A, B, C], interrupt: [D, E]。相当于原先 next: [A, B, C, sub_D, sub_E]，interrupt 始终接在 next 最后面。
- [x] 移除 `runout_next` 等使流程变得混乱的字段
- [x] #246
- [x] #285
- [x] #286
- [x] #283
- [ ] ~~尽可能统一 CustomRecognizer 和 CustomAction~~
- [ ] ~~ProjectInterface 解耦，作为单独的库提供 #317~~
- [ ] ~~尝试提供 MaaPiGui~~
- [x] 允许 Pipeline 属性字段的默认值全局改变
- [x] toolkit Find 系列接口重构
- [x] ROI target, ROI offset
- [x] `on_error` instead of `timeout_next`
- [x] 识别速率限制
- [x] Android Release
- [x] MaaPiCli 的自定义注册接口
- [x] ~~更多的回调事件？~~
- [x] SetNext 接口？
- [ ] ~~ListBuffer 泛型？~~

## 肝不完了，剩下的 2.1 再说（

- [ ] #298
- [ ] https://github.com/MaaXYZ/MaaFramework/issues/57
- [ ] 不同比例分辨率的 ROI 解法
- [x] mumu 模拟器 后台保活支持
- [x] 雷电模拟器 截图接口支持
- [ ] Touch 系列 action

**Comment by MistEO** [comment]
```jsonc
{
	"TaskA": {
		"next": [
			"TaskB",
			{
				"name": "TaskC",
				"is_sub": true,
				"next": [
					"TaskD"
				]
			},
			"TaskC"
		]
	}
}
```

天才！

**Comment by MistEO** [comment]
> `enabled`, `times_limit` 作为next属性，diff该怎么写，难道要重写一长串next（？）

我想到了这点，所以我删了这条（）

**Comment by neko-para** [comment]
timeout直接移除了?

**Comment by skrlst** [comment]
> 移除 timeout_next, runout_next 等使流程变得混乱的字段

表示 timeout_next 还是很好用的

**Comment by MistEO** [comment]
timeout 的思路有问题，对于用户来说就是看着脚本卡了 20 秒，我觉得这种体验不好。应该更多的增加中间过程以及异常情况识别

**Comment by neko-para** [comment]
ProjectInterface目前来看复杂度有限, 感觉没必要作为库, 只需要规定一个spec让需要使用的自己实现就行吧
如果库只提供执行能力, 那就需要倒过来嵌入配置, 而且无法获取中间状态(比如, 单纯需要resource/controller)
如果库提供比较完整的编辑处理能力, 库本身的复杂度又过高了, 不如直接实现吧

**Comment by moomiji** [comment]
允许 Pipeline 属性字段的默认值全局改变

**Comment by neko-para** [comment]
我还是觉得干脆点直接用字符串来作为controller的type比较好(
不管是用StringListBuffer还是用个啥逗号分隔之类的 :thinking:

**Comment by SweetSmellFox** [comment]
没有timeout_next的话，假如任务过程遇到类似于明日方舟闪退或者是明日方舟闪断更新这种情况的话该怎么处理

**Comment by moomiji** [comment]
is sub 改成任务异常，并考虑全局异常

**Comment by MistEO** [comment]
> 没有timeout_next的话，假如任务过程遇到类似于明日方舟闪退或者是明日方舟闪断更新这种情况的话该怎么处理

添加一个全局异常处理机制

**Comment by weinibuliu** [comment]
我用is_sub主要是为了方便复用任务而不是异常处理，删掉之后配置next与catch（？）好像会有点麻烦的样子orz

**Comment by bamboo98** [comment]
pipeline支持图形化节点编程(连连看)
强烈要求保留timeout_next, runout_next,最起码保留到3.0再移除(

**Comment by neko-para** [comment]
> pipeline支持图形化节点编程(连连看)

这个你应该一个具体的开发辅助工具下面提，fw又没有官方编辑器

**Comment by moomiji** [comment]
小测了下 Android API Level 的兼容性：
- 26 及以上，MaaFramework 的行为具有一致性
- 23 及以上，MaaTouch 可用
- 21 及以上，MaaFramework 功能正常
- 18 & 19，获取截图功能正常，仅 ScreencapEncodeToFile 可用，pipeline 运行会持续报错（见下文）
- 17 及以下，截图为空图，不排除测试环境问题或修改 controller_config 可用

``` basic
18 & 19
[2024-07-08 09:46:33.633][ERR][Px7237][Tx46592][UnitBase.cpp][L65][std::optional<std::string> MaaNS::CtrlUnitNs::UnitBase::startup_and_read_pipe(const ProcessArgv &, std::chrono::seconds)] child return error [argv.exec=/Users/runner/Library/Android/sdk/platform-tools/adb] [argv.args=["-s","emulator-5554","exec-out","screencap -p"]] 
[2024-07-08 09:46:33.633][ERR][Px7237][Tx46592][ControlUnitMgr.cpp][L290][bool MaaNS::CtrlUnitNs::ControlUnitMgr::_screencap(cv::Mat &)] failed to screencap 
[2024-07-08 09:46:33.633][ERR][Px7237][Tx46592][GeneralControllerAgent.cpp][L92][virtual std::optional<cv::Mat> MaaNS::ControllerNS::GeneralControllerAgent::_screencap()] controller screencap failed 
[2024-07-08 09:46:33.633][ERR][Px7237][Tx46592][ControllerAgent.cpp][L538][bool MaaNS::ControllerNS::ControllerAgent::handle_screencap()] controller screencap failed 
[2024-07-08 09:46:33.633][ERR][Px7237][Tx41195][PipelineTask.cpp][L220][std::optional<PipelineTask::HitDetail> MaaNS::TaskNS::PipelineTask::find_first(const std::vector<std::string> &)] Image is empty 
```

**Comment by overflow65537** [comment]
roi_target能加入到2.0中吗
通过继承上一个程序的识别结果来作为roi

**Comment by MistEO** [comment]
`timeout_next` 保留兼容性 [`51d1227` (#324)](https://github.com/MaaXYZ/MaaFramework/pull/324/commits/51d12278f899cb1a903d20d7fd8ea0b749e21f61)

**Comment by Yebolin** [comment]
`StartApp
启动 App 。

该动作属性需额外部分字段：

package: string
启动入口。必选。
需要填入 package name 或 activity ，例如 com.hypergryph.arknights 或 com.hypergryph.arknights/com.u8.sdk.U8UnityContext 。`
这个可以支持更多的参数么？
例如对于mumu有应用分身的，如果想启动分身的应用需要**指定启动的用户** `am start --user 10 -n ACTIVITY`，这样就可以不多开模拟器实现2个（最多好像是9个）应用的共存，尤其是对于不支持账号切换的app（例如森空岛）的多账号支持。

**Comment by neko-para** [comment]
> > StartApp
> >
> >启动 App 。
> >
> >该动作属性需额外部分字段：
> >
> >package: string
> >启动入口。必选。
> >需要填入 package name 或 activity ，例如 com.hypergryph.arknights 或com.hypergryph.arknights/com.u8.sdk.U8UnityContext `
> 
> 这个可以支持更多的参数么？
> 例如对于mumu有应用分身的，如果想启动分身的应用需要**指定启动的用户** `am start --user 10 -n ACTIVITY`，这样就可以不多开模拟器实现2个（最多好像是9个）应用的共存，尤其是对于不支持账号切换的app（例如森空岛）的多账号支持。

这个可以考虑单独开个feature request的issue

**Comment by MistEO** [comment]
> > StartApp
> > 启动 App 。
> > 该动作属性需额外部分字段：
> > package: string
> > 启动入口。必选。
> > 需要填入 package name 或 activity ，例如 com.hypergryph.arknights 或com.hypergryph.arknights/com.u8.sdk.U8UnityContext `
> 
> 这个可以支持更多的参数么？ 例如对于mumu有应用分身的，如果想启动分身的应用需要**指定启动的用户** `am start --user 10 -n ACTIVITY`，这样就可以不多开模拟器实现2个（最多好像是9个）应用的共存，尤其是对于不支持账号切换的app（例如森空岛）的多账号支持。

我觉得这种需求可以用 custom 解决（
