### ISSUE TITLE
click动作的位置出现偏差

### ISSUE THREAD

**Issue by nembx** [MaaXYZ/MaaFramework#257]
蓝叠模拟器分辨率1600 X 900，使用OCR识别图片，执行action动作点击的位置会向左偏离，从而使后续任务无法执行
![Snipaste_2024-06-13_12-19-02](https://github.com/MaaXYZ/MaaFramework/assets/123365683/935525b8-2774-4823-a004-6d5158c2e94d)
![Snipaste_2024-06-13_12-26-01](https://github.com/MaaXYZ/MaaFramework/assets/123365683/df92a0ae-72c5-4c32-81df-937ad0d2ff66)
bash报错的信息是说分辨率问题

**Comment by MistEO** [comment]
log发一下，debug/maa.log

**Comment by nembx** [comment]
[maa.log](https://github.com/user-attachments/files/15814661/maa.log)

**Comment by tfft2126** [comment]
@MistEO  v1.8.5的fix， debug了一下分辨率似乎是反了

**Comment by MistEO** [comment]
这个问题修过了，更新一下试试

**Comment by tfft2126** [comment]
> 这个问题修过了，更新一下试试

我的意思是修之前才是对的。。我是用竖屏测的

**Comment by MistEO** [comment]
https://stackoverflow.com/questions/10040624/check-if-device-is-landscape-via-adb
https://stackoverflow.com/questions/26955086/android-adb-commandline-tool-get-orientation

见鬼，这两个说的不一样。给我整蒙了

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/issues/252

这方法看起来不可靠，这还有个横屏但是 orientation 是 0 的

**Comment by tfft2126** [comment]
> #252
> 
> 这方法看起来不可靠，这还有个横屏但是 orientation 是 0 的

是的，不同模拟器的结果可能不一样

**Comment by nembx** [comment]
并没有解决问题，哥们

**Comment by MistEO** [comment]
log 发出来，不然我给你算一卦吗

**Comment by nembx** [comment]
[maa.log](https://github.com/user-attachments/files/15831593/maa.log)

**Comment by MistEO** [comment]
更新一下，你的 log 从始至终都是 v1.8.4

**Comment by nembx** [comment]
@MistEO MAAdebugger的问题，启动MaaPiCli.exe显示的是v1.8.7，而打开MAA就是v1.8.4，这种情况怎么解决
![1](https://github.com/MaaXYZ/MaaFramework/assets/123365683/b0a580ba-6081-4f03-bbc7-09c9930a123d)
![2](https://github.com/MaaXYZ/MaaFramework/assets/
[maa.log](https://github.com/user-attachments/files/15845500/maa.log)
123365683/84b258f3-93b1-49ee-aee8-a23c827a7f6f)
[maa.log](https://github.com/user-attachments/files/15845503/maa.log)

**Comment by MistEO** [comment]
pip install maafw --upgrade
