### ISSUE TITLE
MaaWin32的InputText不能正确输入指定内容

### ISSUE THREAD

**Issue by YYDKyun** [MaaXYZ/MaaFramework#259]
MaaWin32的InputText不能正确输入指定内容，并且会修改win32窗口标题
出现问题位置包括:
1. 任务流水线中直接定义
2. 使用自定义任务SyncContext.input_text
controller参数touch_type=MaaWin32ControllerTypeEnum.Touch_SendMessage,
                                 key_type=MaaWin32ControllerTypeEnum.Key_SendMessage,
                               screencap_type=MaaWin32ControllerTypeEnum.Screencap_DXGI_FramePool
Pipeline内容
[sample.json](https://github.com/user-attachments/files/15837331/sample.json)
自定义任务
![Snipaste_2024-06-14_19-26-49](https://github.com/MaaXYZ/MaaFramework/assets/118797870/da42ac63-bcc3-4951-b231-661b7c9a19c0)
原始窗口标题
![原始标题](https://github.com/MaaXYZ/MaaFramework/assets/118797870/19aae3a2-9f48-49af-b379-0e6bcc75d299)
被修改后窗口标题
![被修改后标题](https://github.com/MaaXYZ/MaaFramework/assets/118797870/25230727-f32c-420f-9cf6-4037031558de)

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/blob/main/source/MaaWin32ControlUnit/Input/SendMessageInput.cpp#L127

这个似乎不 work，等个大佬带带
