### ISSUE TITLE
任务json里写的识别并点击"资源"结果点击到"进度"

### ISSUE THREAD

**Issue by mm317670** [MaaXYZ/MaaFramework#260]
任务json里写的识别并点击"资源"结果是识别到"资源"，点击"进度"。。（录屏软件出问题了，只能手机录一个了）（"resource"是我写的任务json）
[maa.log](https://github.com/user-attachments/files/15846412/maa.log)

https://github.com/MaaXYZ/MaaFramework/assets/142766247/ecbf615b-3156-4571-9e89-ee7e8c243975

![QQ图片20240615180512](https://github.com/MaaXYZ/MaaFramework/assets/142766247/585188f3-db9b-4b17-a923-5778e8cb2795)
![QQ图片20240615180526](https://github.com/MaaXYZ/MaaFramework/assets/142766247/472372a9-64b6-447c-bedb-60be9b7a2678)
[resource.json](https://github.com/user-attachments/files/15846424/resource.json)
![QQ图片20240615180742](https://github.com/MaaXYZ/MaaFramework/assets/142766247/7407e829-8a8e-4894-b5b5-7e6afce7a058)

**Comment by MistEO** [comment]
试试这个包是不是修复了 https://github.com/MaaXYZ/MaaFramework/actions/runs/9529206667

**Comment by mm317670** [comment]
可以了，感谢~

**Comment by MistEO** [comment]
OK之后的版本会带上这个修复，到时候更新一下就行。目前可以先拿这个包开发调试
