### ISSUE TITLE
MaaPiCli 程序是否支持一键运行

### ISSUE THREAD

**Issue by xiaofeiTM233** [MaaXYZ/MaaFramework#268]
如题，MaaPiCli.exe 是否支持一键运行，比如传入一个`-6`参数启动之后就跳过输入阶段，自动开始 Run tasks
目前好像只能手动输入？（没看到哪里说可以一键运行）
![image](https://github.com/MaaXYZ/MaaFramework/assets/55832499/7c5001a0-e53d-4ee6-be29-034e03c5c98a)

**Comment by moomiji** [comment]
生成了配置文件后，支持 `-d` 直接运行

**Comment by xiaofeiTM233** [comment]
原来-d可以吗，想着-6选择第六个去了……
