### ISSUE TITLE
使用特征匹配出现报错

### ISSUE THREAD

**Issue by YiYueHuYu** [MaaXYZ/MaaFramework#275]
首先是在debug阶段只要使用了特征匹配的功能就会出现中断debugger网页连接的情况 这是对应的报错截图
![debugger报错](https://github.com/MaaXYZ/MaaFramework/assets/118604215/77c01dd7-cb59-46ec-8c8b-b66cdf9459da)

然后尝试去打包运行 也会出现报错的页面
![打包报错](https://github.com/MaaXYZ/MaaFramework/assets/118604215/0f5fbfe4-7202-4d30-a586-75473f09a2a1)
暂时不明错误发生原因
这是打包运行过程中的日志
[maa.log](https://github.com/user-attachments/files/16115494/maa.log)

**Comment by MistEO** [comment]
这张图片发一下看看

**Comment by YiYueHuYu** [comment]
哪张？

**Comment by YiYueHuYu** [comment]
> 这张图片发一下看看
哪张？

**Comment by YiYueHuYu** [comment]
发现我打包的时候任务名称打错了 我再重新传一个新的打包报错图和日志

![新的打包报错](https://github.com/MaaXYZ/MaaFramework/assets/118604215/b4c5d5fb-aa7d-479a-a383-b4f4ad38ad87)
[新的日志文件.log](https://github.com/user-attachments/files/16115658/default.log)

也是跟调试网页一样 跳出这两行文字之后就会直接关闭弹窗了

**Comment by Jash1787** [comment]
[https://github.com/MaaXYZ/MaaFramework/issues/226](url)
可以参考 Issue 226，可能是你的 Source 图档 OpenCV 无法读取，试试重新截图然后用 Maa 的截图工具制作 Source 图档。

**Comment by YiYueHuYu** [comment]
> [https://github.com/MaaXYZ/MaaFramework/issues/226](url) 可以参考 Issue 226，可能是你的 Source 图档 OpenCV 无法读取，试试重新截图然后用 Maa 的截图工具制作 Source 图档。

图像匹配是可以正常用的 但是如果变成特征匹配就会出现如上问题 所有截图都是使用的maa截图工具

**Comment by MistEO** [comment]
> > 这张图片发一下看看
> > 哪张？

发生错误的这张模板图片

**Comment by MistEO** [comment]
["识别一条","点击战斗","寻找战斗"]

没看出来是哪个，这几个的图片都发下看看

**Comment by YiYueHuYu** [comment]
> ["识别一条","点击战斗","寻找战斗"]
> 
> 没看出来是哪个，这几个的图片都发下看看

第一个任务是文字识别 后面两个任务的图片识别都是同一个，下面这个是识别的图片
![战斗问号](https://github.com/MaaXYZ/MaaFramework/assets/118604215/866945ab-4ea9-4c11-9053-99bf99328f6a)

**Comment by MistEO** [comment]
这个图太小了，特征太少，特征识别不需要这么干净的图，弄大一点。崩溃的问题后面版本会修一下，不过这张图还是不会有匹配结果的

**Comment by YiYueHuYu** [comment]
> 这个图太小了，特征太少，特征识别不需要这么干净的图，弄大一点。崩溃的问题后面版本会修一下，不过这张图还是不会有匹配结果的

只是这个示例尝试中使用这个图 我之前也有用别的那种色图去调试 也是失败 当时以为是我性能没跟上
大概是这样的图
![小松丸_松果](https://github.com/user-attachments/assets/7c09c320-6e00-4a80-9e06-38e4ad702616)

**Comment by MistEO** [comment]
![image](https://github.com/user-attachments/assets/5734d080-d70f-424f-8045-7d08c3f0194f)

这个崩溃问题我这里没复现，确定是问号的这张图？

![image](https://github.com/user-attachments/assets/d973d78b-4b36-4f31-a745-8e3d8ff9f95d)

**Comment by YiYueHuYu** [comment]
> ![image](https://private-user-images.githubusercontent.com/18511905/348782595-5734d080-d70f-424f-8045-7d08c3f0194f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDkxMzYsIm5iZiI6MTcyMTEwODgzNiwicGF0aCI6Ii8xODUxMTkwNS8zNDg3ODI1OTUtNTczNGQwODAtZDcwZi00MjRmLTgwNDUtN2QwOGMzZjAxOTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1NDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MDJiYzIwMjU1Y2NiZmY3NTc1OGQ2NTU1MzAwM2JjNjM4YTZkNTM1ZTI1ZGNmZjlhYmYyNTUxMDFlNDI2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VZ3pb1QcS-5mMb34LCVdgjozyxReyR9kQZiutjPlB20)
> 
> 这个崩溃问题我这里没复现，确定是问号的这张图？你的 pipeline 也发下看看
> 
> ![image](https://private-user-images.githubusercontent.com/18511905/348782448-d973d78b-4b36-4f31-a745-8e3d8ff9f95d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDkxMzYsIm5iZiI6MTcyMTEwODgzNiwicGF0aCI6Ii8xODUxMTkwNS8zNDg3ODI0NDgtZDk3M2Q3OGItNGIzNi00ZjMxLWE3NDUtOGUzZDhmZjlmOTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1NDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMTJlMTQwOGVhZjkwODc4Y2MzYTc2YmE1N2Y1ZjliMWYzOGQ3Mzg1MGE5MzVmNzlkZDJkMDg2Y2E2MTcxZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TX_9kopixQWECauJlEUin15_9yZx2GP00ABvrJOiaWA)

多加几个匹配任务试试 我感觉是复杂度上去造成的崩溃 单个任务我也调试成功过 我是做了系列任务 他连续匹配几个的时候就崩溃

**Comment by YiYueHuYu** [comment]
多加几个匹配任务试试 我感觉是复杂度上去造成的崩溃 单个任务我也调试成功过 我是做了系列任务 他连续匹配几次的时候就崩溃

这是pipeline 目前改动比较多 主要看战斗那个json文件就好了
[启动游戏.json](https://github.com/user-attachments/files/16243693/default.json)
[战斗.json](https://github.com/user-attachments/files/16243694/default.json)
[做日常.json](https://github.com/user-attachments/files/16243695/default.json)
[做周常.json](https://github.com/user-attachments/files/16243696/default.json)
我第一次调试出任务出错就是战斗那里 后来在问号任务中我发现有时候图像匹配不精准 我尝试换成特征匹配又出现这样的错误 才想着来问一下是怎么回事 因为那个图片不大 感觉不太会是我的性能带不起来的问题
