### ISSUE TITLE
[RFC] MaaFW 标准化的高级语言面向对象 binding

### ISSUE THREAD

**Issue by MistEO** [MaaXYZ/MaaFramework#283]
## 总则

binding 可以分为两步：

1. 对 C API 进行标准化的 OOP 封装。由于 MaaFW 接口相对较为稳定，在完成后不需要长期进行维护
2. 在 1 的基础上，解析回调 message, detail json, pipeline_override 等参数，封装成不同的函数及结构。这些字段可能会随着 MaaFW 更新不断变化，需要长期跟进 MaaFW 新版本修改

若您希望为 MaaFW 添加某个语言的封装，可根据自身时间精力等安排，任选一种方式进行

## 标准化接口

- MaaTasker, MaaResource, MaaController 需包装成对象，而非过程化的接口。例如 MaaContextGetTasker 这类的接口，也需要返回对象，而非 handle。可以考虑两种模型：
    1. 增加一个全局 handle - 对象引用 字典，通过 handle 去找原对象再返回。
    4. 对象无状态，仅负责引用 handle，直接创建新对象返回。（可参考 python binding 中 own 字段）
- MaaTaskId, MaaCtrlId, MaaResId 等异步动作 id，不对集成方返回。由 binding 封装成 Job 类，提供 wait, status, get 等方法。
- Job 类需提供可以由本 id 进行操作的所有方法的封装，例如 TaskJob, 需要额外支持 MaaTaskerOverridePipeline，且 get 方法需返回 MaaTaskerGetTaskDetail 查询到的数据的封装
- MaaRecoId, MaaNodeId 等查询类 id，不对集成方返回。由 binding 调用 MaaTaskerGetRecoDetail 等接口查询，并包装成 RecoDetail, NodeDetail 等结构体再返回
- SetOption 中每个枚举拆分成独立的接口，例如 set_screenshot_target_long_side 等，而不将具体枚举提供给集成方
- StringBuffer, ImageBuffer 等缓冲区，不对集成方返回。需要转换成本语言惯用的 string, image 类型再给出
- BindResource, BindController, RegisterCustom 等接口需注意留一份引用，避免 gc

## 额外的解析封装

TODO...

**Comment by MistEO** [comment]
binding 需要分为两步：

1. C API 的直接翻译，不做任何封装。可以不对外提供。
2. 标准化的 OOP 封装，尽可能保证各个语言中 MaaFW 的使用方法几乎一致

**Comment by MistEO** [comment]
## Controller

1. 提供纯虚接口 `Controller`，支持除 Create 外所有 Controller 相关方法
2. 提供 `Win32Controller`, `AdbController` 等，均从 `Controller` 上继承
3. 提供 `post_connect` 方法，调用 `MaaControllerPostConnection`，返回 `Future` 对象
4. 提供 `async connect` 方法，返回 bool
5. 提供 `post_screencap` 方法，调用 `MaaControllerPostScreencap`，返回 `Future` 对象
6. 提供 `async screencap` 方法，返回本语言中的 cv2.Mat 对象
7. 提供 cv2.Mat to Image 静态方法（Image 为本语言主流图片类型）
8. `click`, `swipe` 等等操作，均提供 `post` + `async` 两套方法

**Comment by MistEO** [comment]
## Resource

**Comment by MistEO** [comment]
## Instance

**Comment by MistEO** [comment]
## 其他

**Comment by MistEO** [comment]
下班了明天再写.jpg

**Comment by neko-para** [comment]
> ## Controller
> 
> 1. 提供纯虚接口 `Controller`，支持除 Create 外所有 Controller 相关方法
> 2. 提供 `Win32Controller`, `AdbController` 等，均从 `Controller` 上继承
> 3. 提供 `post_connect` 方法，调用 `MaaControllerPostConnection`，返回 `Future` 对象
> 4. 提供 `async connect` 方法，返回 bool
> 5. 提供 `post_screencap` 方法，调用 `MaaControllerPostScreencap`，返回 `Future` 对象
> 6. 提供 `async screencap` 方法，返回本语言中的 cv2.Mat 对象
> 7. 提供 cv2.Mat to Image 静态方法（Image 为本语言主流图片类型）
> 8. `click`, `swipe` 等等操作，均提供 `post` + `async` 两套方法
> 9. 将 `MaaControllerSetOption` 中每个枚举拆分成独立的接口，例如 `set_screenshot_target_long_side` 等，而不将具体枚举提供给集成方

感觉7这个有点莫名其妙，这为啥要fw这边做

**Comment by neko-para** [comment]
另外，6涉及到一个问题，即image buffer handle要不要暴露。string buffer handle直接展开是没啥问题，单image感觉可以考虑一下

**Comment by MistEO** [comment]
其实我是想着返回 Image 的，这样对集成方好用一点，但感觉又不太对劲，就想有没有 Mat 和 Image 都能返回的方法（

**Comment by MistEO** [comment]
> 另外，6涉及到一个问题，即image buffer handle要不要暴露。string buffer handle直接展开是没啥问题，单image感觉可以考虑一下

深拷贝再返回咯

**Comment by neko-para** [comment]
有一说一, 目前image的raw data相关接口感觉挺尴尬的, 我看py那边也是直接假设一定是8UC3, 但是原理上应该根据type让cv自己来决定取多少

**Comment by moomiji** [comment]
C# 既没有官方cv2库也没有标准跨平台image库（

**Comment by neko-para** [comment]
感觉至少暴露个png是没问题的, cv2/平台Image可以考虑根据语言情况决定

**Comment by neko-para** [comment]
```typescript
type Rect = [number, number, number, number]

declare class Status {
  success(): boolean
  failure(): boolean
  pending(): boolean
  running(): boolean

  done(): boolean
}

declare class Job<Result> {
  status(): Status

  success(): boolean
  failure(): boolean
  pending(): boolean
  running(): boolean

  done(): boolean

  wait(): Promise<boolean>
  get(): Promise<Result>
}

type PlatformSpecificImage = unknown

declare abstract class Controller {
  post_connection(): Job<boolean>
  connect(): Promise<boolean>

  post_screencap(): Job<PlatformSpecificImage>
  screencap(): Promise<PlatformSpecificImage>

  // ...

  set_target_long_side(value: number): boolean
  // ...
}

declare class AdbController {
  create(/* adb related options */): boolean
}

declare class Resource {
  create(): boolean

  post_path(path: string): Job<boolean>
  load(path: string): Promise<boolean>

  clear(): boolean
  hash(): string
  task_list(): string[]
}

type RecoDetail = {
  name: string
  hit: boolean
  hit_box: Rect
  detail: string
  raw: PlatformSpecificImage | null
  draws: PlatformSpecificImage[] | null
}

type NodeDetail = {
  name: string
  completed: boolean
  reco: RecoDetail
}

type TaskDetail = {
  entry: string
  nodes: NodeDetail
}

type PipelineJson = unknown

declare class TaskJob extends Job<boolean> {
  set_param(diff: PipelineJson): boolean
  get_detail(): TaskDetail
}

declare class Instance {
  create(): boolean

  post_task(entry: string, diff: PipelineJson): TaskJob
  run_task(entry: string, diff: PipelineJson): Promise<boolean>

  register_custom_recognizer(name: string, func: unknown): boolean

  inited(): boolean
  running(): boolean

  post_stop(): void
}
```

@MistEO 一个参考定义

没有用setter/getter，感觉这个可以各个语言自行考虑是否使用；Image改成了一个语言自己确认的类型；给Resource，Instance都加了个create，主要是看样子不会基于RAII的逻辑来初始化

大部分配置逻辑都透传了bool，这里是否考虑改成try/throw模型？

**Comment by dantmnf** [comment]
> 提供 `Job` 类，对 `MaaTaskId`, `MaaControllerId`, `MaaResourceId` 提供封装。并提供：

这个疑似跟语言提供的 Promise/Future/Task 功能重复了，async/await 模式语言的 async 函数返回的就是 Promise/Future/Task 这种 awaitable 对象。语言一般允许库作者实现自己的 awaitable，但是大多并不鼓励如此，而是提供可以从外部改变状态的 awaitable 机制（比如 .NET `TaskCompletionSource`、Python `asyncio.Future`、JavaScript `Promise.withResolvers`）。

> 3. `async wait` 方法，轮询等待 done
> 
> 4. `async get` 方法，`await wait()`，并返回某些结果（由具体的派生 Job 实现，下文详述）

在 async/await 模式中，`async` 并不是接口的属性，而是用于声明函数体为（无栈）协程。在协程内对 awaitable 对象进行 await 操作才**可能**会挂起协程并让出线程（异步等待）

---

另外一些语言采用了有栈协程+隐式让出的设计，你这个定义就不适用了（


结论：不要试图统一异步 API，尤其不要试图实现自己的 Promise/Future/Task

**Comment by neko-para** [comment]
> > 提供 `Job` 类，对 `MaaTaskId`, `MaaControllerId`, `MaaResourceId` 提供封装。并提供：
> 
> 这个疑似跟语言提供的 Promise/Future/Task 功能重复了，async/await 模式语言的 async 函数返回的就是 Promise/Future/Task 这种 awaitable 对象。语言一般允许库作者实现自己的 awaitable，但是大多并不鼓励如此，而是提供可以从外部改变状态的 awaitable 机制（比如 .NET `TaskCompletionSource`、Python `asyncio.Future`、JavaScript `Promise.withResolvers`）。
> 
> > 3. `async wait` 方法，轮询等待 done
> > 4. `async get` 方法，`await wait()`，并返回某些结果（由具体的派生 Job 实现，下文详述）
> 
> 在 async/await 模式中，`async` 并不是接口的属性，而是用于声明函数体为（无栈）协程。在协程内对 awaitable 对象进行 await 操作才**可能**会挂起协程并让出线程（异步等待）
> 
> 另外一些语言采用了有栈协程+隐式让出的设计，你这个定义就不适用了（
> 
> 结论：不要试图统一异步 API，尤其不要试图实现自己的 Promise/Future/Task

我感觉玛丽想的其实是在返回的异步结果上包一层以提供像set_param之类的特定方法，这个Job大概并不是Promise语义的东西来着，需要用wait/get来获取实际的Promise。

**Comment by dantmnf** [comment]
> 返回的异步结果上包一层以提供像set_param之类的特定方法

那问题就更大了，对异步操作 set_param 怎么看怎么都有巨大多 racing condition

**Comment by neko-para** [comment]
> 那问题就更大了，对异步操作 set_param 怎么看怎么都有巨大多 racing condition

是，我确实感觉task的set_param这事比较微妙（

以及其它Job基本也没有特殊方法，task的Job这倒是确实需要有一个get_detail这个，如果直接返回语言的Promise，会把底下的task id给吞了，这可能需要看怎么处理一下

**Comment by neko-para** [comment]
要说的话确实可以返回一个[Promise, id]之类的（

**Comment by dantmnf** [comment]
给用户暴露 task id 的用途是？结果直接包在 Promise 里，用于取消那也应该用语言提供的取消机制（CancellationToken/Context 之类的）

**Comment by neko-para** [comment]
> 给用户暴露 task id 的用途是？结果直接包在 Promise 里，用于取消那也应该用语言提供的取消机制（CancellationToken/Context 之类的）

是可以，但是毕竟这玩意获取还是有些成本的（尤其是开了debug之后里面一堆图

**Comment by dantmnf** [comment]
一堆图可以 move ownership，进程内零成本（）

**Comment by neko-para** [comment]
感觉这对大部分FFI实现的binding都有点困难（其实你让我把用napi写的js binding改成这样我好像也搞不定欸

**Comment by dantmnf** [comment]
不就给 owner object 加一个 destructor/finalizer 的事（

**Comment by neko-para** [comment]
但是这得库提供一个分配/释放内存的接口才行（至少目前maafw是没有这玩意的

**Comment by dantmnf** [comment]
另外如果一个语言无法实现 move memory ownership 的机制，那它的用户就应该认知到并接受如此带来的性能损失（逃

**Comment by neko-para** [comment]
@MistEO 查找Adb和Win32的那堆接口, 是不是没必要对外提供, 直接提供一个 查询 - 返回数组 就好了 🤔

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/blob/dev/docs/zh_cn/4.2-%E6%A0%87%E5%87%86%E5%8C%96Binding%E5%8D%8F%E8%AE%AE.md
