### ISSUE TITLE
MaaPP 关于 SyncContext  的非良构设计

### ISSUE THREAD

**Issue by zymelaii** [MaaXYZ/MaaFramework#294]
MaaPP 的 SyncContext 将所有方法封装为了异步方法，这使得在编码上将允许 SyncContext Method 的并发执行。

以 run_recognition 为例：

```c++
std::array<coro::Promise<AnalyzeResult>, 6> tasks;
for (auto &task : task) {
    auto image = ...; //<! make and init image
    task = std::move(context->run_recognition(image, "OCR", ocr_params);
}
...
for (auto &task : task) {
    auto  _ = co_await task->wait();
}
```

上述将构造 run_recognition 亦即 MaaSyncContextRunRecognition 的并发执行，该行为将概率性导致 MaaSyncContextRunRecognition 执行的非法访存（访存 0xffffffffffffffe0），此时的调用堆栈为：

```plain
vcruntime140.dll!!00007ff884b01241
fastdeploy_ppocr_maa.dll!!00007fffcc9ae08a
...
fastdeploy_ppocr_maa.dll!!00007fffcc9a3115
MaaFramework.dll!!00007fffccdbed1e
...
MaaFramework.dll!!00007fffccd8fb66
...
```

建议对 MaaFramework 的 MaaSyncContext 系列方法做线程安全处理，或消除 MaaPP 中 SyncContext 的并发语义。

**Comment by neko-para** [comment]
是, 其实这里算是设计的有点问题, 因为SyncContext系列函数原则上不能并发的
