### ISSUE TITLE
MAA分辨率与设备分辨率不一致

### ISSUE THREAD

**Issue by FSPaul2498** [MaaXYZ/MaaFramework#297]
macOS使用AVD设备分辨率为1080x2400，使用MAA连接AVD识别分辨率为720x1600（来自MaaDebugger）
导致直接使用AVD原生截图功能获得的截图和剪裁 MAA无法匹配。使用MaaDebugger提供的过程截图进行剪裁则可以匹配。

系统环境：
MacBook Pro 14英寸，2023年
macOS Sonoma 14.5
Apple M2 Pro
Python 3.10.14 (by miniforge3)
MaaFW==1.8.9

Android Studio环境：
Android Studio Koala | 2024.1.1 Patch 1
Build #AI-241.18034.62.2411.12071903, built on July 11, 2024
Runtime version: 17.0.11+0-17.0.11b1207.24-11852314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.instant.shutdown=false

AVD配置：
Properties
avd.ini.displayname              Pixel 6 API 31
avd.ini.encoding                 UTF-8
AvdId                            Pixel_6_API_31
disk.dataPartition.size          6442450944
fastboot.chosenSnapshotFile      
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     4
hw.device.hash2                  MD5:3db3250dab5d0d93b29353040181c7e9
hw.device.manufacturer           Google
hw.device.name                   pixel_6
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            portrait
hw.keyboard                      yes
hw.lcd.density                   420
hw.lcd.height                    2400
hw.lcd.width                     1080
hw.mainKeys                      no
hw.ramSize                       2048
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         31
image.sysdir.1                   system-images/android-31/google_apis/arm64-v8a/
PlayStore.enabled                false
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google APIs
tag.displaynames                 Google APIs
tag.id                           google_apis
tag.ids                          google_apis
vm.heapSize                      256

**Comment by MistEO** [comment]
默认是强制缩放到 720p 的，肯定不能使用本地分辨率，不然你的脚本放到其他人电脑上（分辨率不同的）就没法用了

建议使用 [截图工具](https://github.com/MaaXYZ/MaaFramework/blob/main/docs/zh_cn/1.1-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B.md#%E5%9B%BE%E7%89%87%E6%96%87%E4%BB%B6) 进行操作

![image](https://github.com/user-attachments/assets/f845b145-516e-4614-be91-b063833e059a)

如果一定要修改默认分辨率（不推荐修改），可以用 [这个接口](https://github.com/MaaXYZ/MaaFramework/blob/main/source/binding/Python/maa/controller.py#L146)

**Comment by FSPaul2498** [comment]
明白了，因为看到文档前文有提到“请注意所使用的图片需要是无损原图的裁剪。若使用安卓模拟器，请使用模拟器自带的截图功能！”，我默认理解成MAA会直接使用设备原生分辨率，就没有使用下面的工具，而是直接用GIMP做了图片剪裁。
我去使用截图工具尝试下，感谢指路。

**Comment by MistEO** [comment]
@neko-para 该改改文档话术了，两句话确实有点冲突（

**Comment by neko-para** [comment]
阿巴阿巴
