### ISSUE TITLE
VSC 扩展 无法自动填充路径

### ISSUE THREAD

**Issue by weinibuliu** [MaaXYZ/MaaFramework#299]
VSC的扩展支持补全任务字段，但无法补全图片路径（其他功能正不正常就没试过了）

项目文件:[https://www.123pan.com/s/OFAyVv-13uwd.html](https://www.123pan.com/s/OFAyVv-13uwd.html)

**Comment by neko-para** [comment]
经过测试, 其实目前支持补全字段是json schema的功能, 插件功能其实没有生效. 需要手动使用 Ctrl Shift P 打开命令面板, 搜索 Maa: 执行interface 命令, 在其中进行初始化的配置之后才行.
