### ISSUE TITLE
使用 cmake 构建MaaFramework工程出错

### ISSUE THREAD

**Issue by saberlovestme** [MaaXYZ/MaaFramework#301]
PS H:\MAA\MaaFramework> cmake --build build --config Release
适用于 .NET Framework MSBuild 版本 17.10.4+10fbfbf2e

  MaaUtils.vcxproj -> H:\MAA\MaaFramework\build\bin\Release\MaaUtils.dll
  AdbControlUnitAPI.cpp
  ProcessArgvGenerator.cpp
  UnitBase.cpp
  Activity.cpp
  Connection.cpp
  DeviceInfo.cpp
  DeviceList.cpp
  AdbInput.cpp
  AutoDetectInput.cpp
  MaatouchInput.cpp
  MinitouchInput.cpp
  MtouchHelper.cpp
H:\MAA\MaaFramework\source\MaaAdbControlUnit\EmulatorExtras\MumuExternalRendererIpc.h(3,10): error C1083: 无法打开包括文件: “Mumu/external_renderer_ipc/external_renderer_ipc.h”: No such f
ile or directory [H:\MAA\MaaFramework\build\source\MaaAdbControlUnit\MaaAdbControlUnit.vcxproj]
  InvokeApp.cpp
H:\MAA\MaaFramework\source\MaaAdbControlUnit\EmulatorExtras\MumuExternalRendererIpc.h(3,10): error C1083: 无法打开包括文件: “Mumu/external_renderer_ipc/external_renderer_ipc.h”: No such f
ile or directory [H:\MAA\MaaFramework\build\source\MaaAdbControlUnit\MaaAdbControlUnit.vcxproj]
  ControlUnitMgr.cpp
  Encode.cpp
  EncodeToFile.cpp
  FastestWay.cpp
  MinicapBase.cpp
  MinicapDirect.cpp
H:\MAA\MaaFramework\source\MaaAdbControlUnit\EmulatorExtras\MumuExternalRendererIpc.h(3,10): error C1083: 无法打开包括文件: “Mumu/external_renderer_ipc/external_renderer_ipc.h”: No such f
ile or directory [H:\MAA\MaaFramework\build\source\MaaAdbControlUnit\MaaAdbControlUnit.vcxproj]
  MinicapStream.cpp
  RawByNetcat.cpp
  RawWithGzip.cpp
  ScreencapHelper.cpp
  MaaDbgControlUnit.vcxproj -> H:\MAA\MaaFramework\build\bin\Release\MaaDbgControlUnit.dll
  MaaWin32ControlUnit.vcxproj -> H:\MAA\MaaFramework\build\bin\Release\MaaWin32ControlUnit.dll
  ProjectInterface.vcxproj -> H:\MAA\MaaFramework\build\lib\Release\ProjectInterface.lib
PS H:\MAA\MaaFramework> 

是缺少Mumu/external_renderer_ipc/external_renderer_ipc.h 文件吗？

**Comment by MistEO** [comment]
你没 clone 子模块

**Comment by saberlovestme** [comment]
好的，谢谢
