### ISSUE TITLE
context.run_recognize() 工作不正常

### ISSUE THREAD

**Issue by awei-nan** [MaaXYZ/MaaFramework#303]
## 代码报错
![9f67344288f2d6c314ae0072a24680e1_0](https://github.com/user-attachments/assets/9a2a93f3-fd1d-44d1-ab94-caabcc150ba9)
## 代码内容
![7cf11bb40f0bbadfe1568b61b2e3c9a2_0](https://github.com/user-attachments/assets/147ca846-021c-460e-a0d9-8349bf1a8c32)
## 不会报错的写法：
![60b7795638b99b303e3b9ee4d5e45dbb_0](https://github.com/user-attachments/assets/3eb0c47e-8d45-426d-bd74-b164330a2152)
![image](https://github.com/user-attachments/assets/5a8ff53a-eefe-4888-8220-7ea72644b1ce)
## roi问题
当roi设置为[0,0,0,0]即全屏时，上述三种方法都会报错

**Comment by MistEO** [comment]
试试 2.0
