### ISSUE TITLE
MaaToolkitRegisterCustomXXXExecutor系列函数没有正确地和实例关联

### ISSUE THREAD

**Issue by neko-para** [MaaXYZ/MaaFramework#306]
目前的实现中, ExecAgent的配置信息是通过单例在维护, 对任何实例进行注册会写入到同一个map中, 导致两个实例注册同名ExecAgent会导致后者失败.

**Comment by MistEO** [comment]
2.0 就没这个问题了（

https://github.com/MaaXYZ/MaaFramework/issues/246
