### ISSUE TITLE
ImageCropper 保存后cv2.getWindowProperty销毁窗口异常

### ISSUE THREAD

**Issue by hmbool** [MaaXYZ/MaaFramework#307]
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/c1dc4c3f-e22b-42d1-bf62-e1245366f89e">

将 cv2.WND_PROP_VISIBLE 换成 cv2.WND_PROP_AUTOSIZE 后解决报错
<img width="607" alt="image" src="https://github.com/user-attachments/assets/cd83bfeb-0c7b-46b9-90d9-f0f01ffb200d">

不知道是不是窗口状态这个问题，pr就不提了(

**Comment by neko-para** [comment]
看看报错, 你正好把错误截掉了

**Comment by hmbool** [comment]
> 看看报错, 你正好把错误截掉了
<img width="570" alt="image" src="https://github.com/user-attachments/assets/6f05afea-9292-4489-a7c0-fe92cc82748c">

**Comment by hmbool** [comment]
@ [neko-para](https://github.com/neko-para)

**Comment by neko-para** [comment]
@moomiji

**Comment by moomiji** [comment]
系统是 macos ？

**Comment by neko-para** [comment]
是，看cv底层用的cocoa

**Comment by moomiji** [comment]
我这没测试环境诶

看看按 <kbd>C</kbd>键弹出取色窗口后，再按 <kbd>R</kbd> 键会不会报错
