### ISSUE TITLE
interface.json 中如何指定 exec_agent 并使用？

### ISSUE THREAD

**Issue by Starseeker-H** [MaaXYZ/MaaFramework#322]
注意到 sample/interface.json 中 存在 ```recognizer``` 字段，似乎是指定了某个位置的 ```__main__.py``` 为执行器代理形式的自定义识别器（但sample里面并没有这个脚本），目前使用 interface.json 的似乎只有项目模板和vscode插件，但尝试在interface里配置好识别器后（仿照 sample/python/exec_agent/my_action.py 直接返回True），插件似乎是不认这个识别器，尝试在pipeline里的任务上应用识别器，vscode里直接点击执行，全都执行失败，Maa Support返回 Hit: false。

（另，interface.json 这玩意绝对是最需要文档的东西之一吧，完全不知道每部分是干什么的）

**Comment by dongwlin** [comment]
https://github.com/MaaXYZ/MaaFramework/blob/main/tools/interface.schema.json
这就是interface.json的文档（确信

**Comment by neko-para** [comment]
> interface.json 的似乎只有项目模板和vscode插件，但尝试在interface里配置好识别器后（仿照 sample/python/exec_agent/my_action.py 直接返回True），插件似乎是不认这个识别器，尝试在pipeline

看看interface咋写的

**Comment by Starseeker-H** [comment]
[interface.json](https://github.com/user-attachments/files/16888024/interface.json)
[exec_agent.zip](https://github.com/user-attachments/files/16888044/exec_agent.zip)
就放在assets下面，之前有一次什么都没改就重启了一下，莫名其妙成功弹窗出来了，也没法复现

**Comment by Starseeker-H** [comment]
> > interface.json 的似乎只有项目模板和vscode插件，但尝试在interface里配置好识别器后（仿照 sample/python/exec_agent/my_action.py 直接返回True），插件似乎是不认这个识别器，尝试在pipeline
> 
> 看看interface咋写的

[interface.json](https://github.com/user-attachments/files/16888205/interface.json)

[exec_agent.zip](https://github.com/user-attachments/files/16888201/exec_agent.zip)

就放在 assets下面，之前有一次什么都没改，就重启了一下，结果成功运行了？？也不知道怎么复现

**Comment by MistEO** [comment]
2.0 计划删了 exec agent，不急可以等等新接口（
