### ISSUE TITLE
Swipe动作的duration字段无法生效

### ISSUE THREAD

**Issue by shanchuan001** [MaaXYZ/MaaFramework#328]
无论duration设置多少,都不起效果
[maa.log](https://github.com/user-attachments/files/16909168/maa.log)

**Comment by MistEO** [comment]
![image](https://github.com/user-attachments/assets/fdbce658-e633-4f6d-870d-760b15bf9946)

**Comment by shanchuan001** [comment]
已经解决,非常感谢
