### ISSUE TITLE
全都执行一遍的列表？（和 next 相对的）

### ISSUE THREAD

**Issue by MistEO** [MaaXYZ/MaaFramework#344]

**Comment by MistEO** [comment]
需要考虑：其中某一个报错的时候，怎么处理

**Comment by dongwlin** [comment]
next里面再套一层数组？

像这样

```json
{
    "TaskA": {
        "next": [
            ["TaskB","TaskC"]
        ]
    },
    "TaskB": {
        "doc": "do something"
    },
    "TaskC": {
        "doc": "do something"
    }
}
```

但感觉这样就像把里面的数组另外遍历run pipeline一样。

**Comment by Night-stars-1** [comment]
> 需要考虑：其中某一个报错的时候，怎么处理

其中一个报错，感觉这个报错的task可以直接返回null，继续执行下一个。
这个全部执行一遍的列表使用的是同一张图片，这个列表不会出现对屏幕的操作，所以返回null也没有影响

**Comment by MistEO** [comment]
不一样，执行列表里使用同一张图片可以，但它们的 next 怎么办？

我感觉这个需求又让 Pipeline 变复杂了，要不还是靠 Custom 让开发者自己写吧
