### ISSUE TITLE
RawByNetcat accept timeout 后卡住

### ISSUE THREAD

**Issue by aaaasssddf** [MaaXYZ/MaaFramework#349]
![image](https://github.com/user-attachments/assets/9b3fb405-e01f-4477-9577-5bb58d010c56)
系统是Ubuntu24.04
模拟器是redroid11.0
M9A版本2.0.0.-alpha2和2.0.0-alpha3都会报这个错
maa可以启动同一个模拟器里的明日方舟，而且使用命令行adb connect也是成功的，在另一台同局域网下的电脑使用QtScrcpy也可以连上，但是M9A只报了这一行错而且没用任何动作。
剩下几个跟这个报错类似情况的issue看过了但是情况好像不太一样。
在同一局域网下的windows电脑使用MaaPiCli连接则是Run Tasks之后程序直接退出
应该不是adb的问题，adb改成别的都会有不同的报错
可能是redroid和M9A适配的问题之类的？

**Comment by MistEO** [comment]
一个临时的解决方法，先把你设备上不能用的这种截图方法屏蔽掉

在 interface.json 文件里里的把 controller 改成这样

```json
    "controller": [
        {
            "name": "ADB 默认方式",
            "type": "Adb",
            "adb": {
                "screencap": 7
            }
        }
    ],
```

![image](https://github.com/user-attachments/assets/2cef5f90-127c-44f2-b562-18a0e8240624)

**Comment by aaaasssddf** [comment]
修改完interface.json后可以正常运行并报了一些templ size is too large的错误
![image](https://github.com/user-attachments/assets/cc4deb6f-36c3-4d21-b1ce-8373c80e6875)

**Comment by MistEO** [comment]
你的画面咋是竖屏的，截到的图是 720*1280

**Comment by aaaasssddf** [comment]
> 你的画面咋是竖屏的，截到的图是 720*1280

哦我知道了，把redroid加上宽度和高度的参数启动再使用M9A就没有这些报错了只剩下最后那两条

**Comment by MistEO** [comment]
log 发一下

**Comment by aaaasssddf** [comment]
[maa.log](https://github.com/user-attachments/files/17040240/maa.log)
680行左右

**Comment by neko-para** [comment]
这个bug之前mac遇到过一次(

**Comment by MistEO** [comment]
> [maa.log](https://github.com/user-attachments/files/17040240/maa.log) 680行左右

`/usr/bin/adb -s 127.0.0.1:5555 shell dumpsys input | grep SurfaceOrientation | grep -m 1 -o -E [0-9]` 这个命令在你的设备上跑不了，是用来获取屏幕旋转方向的。不过貌似没啥影响，取了个默认值 0 去用了，后续的控制都正常吗？

**Comment by aaaasssddf** [comment]
> > [maa.log](https://github.com/user-attachments/files/17040240/maa.log) 680行左右
> 
> `/usr/bin/adb -s 127.0.0.1:5555 shell dumpsys input | grep SurfaceOrientation | grep -m 1 -o -E [0-9]` 这个命令在你的设备上跑不了，是用来获取屏幕旋转方向的。不过貌似没啥影响，取了个默认值 0 去用了，后续的控制都正常吗？

貌似没别的问题

**Comment by MistEO** [comment]
搞不懂，改用 boost acceptor::async_accept 之后 future 倒是能退出来了，但是原本能正常连接的设备却又连不上了。。

总之先在非 Windows 下屏蔽了这个方法

**Comment by neko-para** [comment]
早该突突了（

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/commit/cf441aa78bb2b472cb742e23ede9789ae8122064
