### ISSUE TITLE
[MAA-win-x86_64] 动态链接库(DLL)初始化例程失败

### ISSUE THREAD

**Issue by hanhuoer** [MaaXYZ/MaaFramework#361]
## 环境

Windows 10
版本 10.0.19045
系统类型 基于 x64 的电脑
处理器 Intel(R) Core(TM) i7-6700HQ CPU
Java 11

## 描述

最近在做 [maa-framework-java](https://github.com/hanhuoer/maa-framework-java) 的版本升级，发现在 Windows 平台总是出现动态链接库初始化失败的错误。

无论是何“姿势”反复卸载/安装/重启 [Latest Microsoft Visual C++ Redistributable Version](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version) 都无法解决此问题，下面有截图安装的情况。

奇怪的是，此前 `1.8.8` `1.8.9` 两个版本都是正常集成，没有见到过这个错误，但在 `2.0.0` 系列（alpha/beta/release）都是这个情况，总提示我动态链接库错误。

是新版有什么对接方式上的调整吗（Windows）？

哦对了，我在 `MacOS aarch64` 平台上测试 `2.0.0` 系列的时候可以正常加载本地库。

<details>
<summary>展开查看截图</summary>
<pre>
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/38f45abb-9f4d-4988-8c2e-e8ccf6dafa91">
</pre>
</details>

## 相关问题

- [[win32-x86-64] Unable to load library MaaFramework.dll #1 - maa-framework-java](https://github.com/hanhuoer/maa-framework-java/issues/1#issuecomment-2365185993)
- [大佬有更新2.0的计划吗？ #2 - maa-framework-java](https://github.com/hanhuoer/maa-framework-java/issues/2#issuecomment-2367354503)
- [找不到动态链接库问题 #233 - MaaFramework](https://github.com/MaaXYZ/MaaFramework/issues/233#issuecomment-2119231180)

**Comment by moomiji** [comment]
来点 java 详细报错

**Comment by hanhuoer** [comment]
> 来点 java 详细报错

由于这个原因，导致 github 无法上传最小 demo `File size too big: 25 MB are allowed, 35 MB were attempted to upload.`

所以，这里附上蓝奏云链接 [https://wwxq.lanzoue.com/iLmrj2aolskb - [36MB]](https://wwxq.lanzoue.com/iLmrj2aolskb)

图片一直传不上来，贴一下日志吧 ⬇️⬇️⬇️

```log
D:\Tools\Java\RedHat\java-11-openjdk-11.0.8-2\bin\java.exe "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2023.2.3\lib\idea_rt.jar=11269:D:\Program Files\JetBrains\IntelliJ IDEA 2023.2.3\bin" -Dfile.encoding=UTF-8 -classpath D:\Programs\Gogs\MAA\demo\target\classes;D:\Tools\\MavenRepository\net\java\dev\jna\jna\5.15.0\jna-5.15.0.jar com.exp.App
9月 23, 2024 5:36:42 下午 com.sun.jna.Native extractFromResourcePath
信息: Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@1f89ab83 for /com/sun/jna/win32-x86-64/jnidispatch.dll
9月 23, 2024 5:36:43 下午 com.sun.jna.Native extractFromResourcePath
信息: Found library resource at jar:file:/D:/Tools/Coder/Developer_tools/MavenRepository/net/java/dev/jna/jna/5.15.0/jna-5.15.0.jar!/com/sun/jna/win32-x86-64/jnidispatch.dll
9月 23, 2024 5:36:43 下午 com.sun.jna.Native extractFromResourcePath
信息: Extracting library to C:\Users\H\AppData\Local\Temp\jna-72\jna3519739205846157609.dll
9月 23, 2024 5:36:43 下午 com.sun.jna.Native loadNativeDispatchLibraryFromClasspath
信息: Trying C:\Users\H\AppData\Local\Temp\jna-72\jna3519739205846157609.dll
9月 23, 2024 5:36:43 下午 com.sun.jna.Native loadNativeDispatchLibraryFromClasspath
信息: Found jnidispatch at C:\Users\H\AppData\Local\Temp\jna-72\jna3519739205846157609.dll
9月 23, 2024 5:36:43 下午 com.sun.jna.NativeLibrary loadLibrary
信息: Looking for library 'D:\Programs\Gogs\MAA\demo\lib\2.0.0\MaaFramework.dll'
9月 23, 2024 5:36:43 下午 com.sun.jna.NativeLibrary loadLibrary
信息: Adding paths from jna.library.path: null
9月 23, 2024 5:36:43 下午 com.sun.jna.NativeLibrary loadLibrary
信息: Trying D:\Programs\Gogs\MAA\demo\lib\2.0.0\MaaFramework.dll
9月 23, 2024 5:36:47 下午 com.sun.jna.NativeLibrary loadLibrary
信息: Loading failed with message: 动态链接库(DLL)初始化例程失败。

9月 23, 2024 5:36:47 下午 com.sun.jna.NativeLibrary loadLibrary
信息: Adding system paths: []
9月 23, 2024 5:36:47 下午 com.sun.jna.NativeLibrary loadLibrary
信息: Trying D:\Programs\Gogs\MAA\demo\lib\2.0.0\MaaFramework.dll
9月 23, 2024 5:36:49 下午 com.sun.jna.NativeLibrary loadLibrary
信息: Loading failed with message: 动态链接库(DLL)初始化例程失败。

9月 23, 2024 5:36:49 下午 com.sun.jna.Native extractFromResourcePath
信息: Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@1f89ab83 for D:\Programs\Gogs\MAA\demo\lib\2.0.0\MaaFramework.dll
9月 23, 2024 5:36:49 下午 com.sun.jna.NativeLibrary loadLibrary
信息: Loading failed with message: Native library (win32-x86-64/D:\Programs\Gogs\MAA\demo\lib\2.0.0\MaaFramework.dll) not found in resource path (D:\Programs\Gogs\MAA\demo\target\classes;D:\Tools\MavenRepository\net\java\dev\jna\jna\5.15.0\jna-5.15.0.jar)
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'D:\Programs\Gogs\MAA\demo\lib\2.0.0\MaaFramework.dll':
动态链接库(DLL)初始化例程失败。

动态链接库(DLL)初始化例程失败。

Native library (win32-x86-64/D:\Programs\Gogs\MAA\demo\lib\2.0.0\MaaFramework.dll) not found in resource path (D:\Programs\Gogs\MAA\demo\target\classes;D:\Tools\MavenRepository\net\java\dev\jna\jna\5.15.0\jna-5.15.0.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:325)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:481)
	at com.sun.jna.Library$Handler.<init>(Library.java:197)
	at com.sun.jna.Native.load(Native.java:618)
	at com.sun.jna.Native.load(Native.java:592)
	at com.exp.App$MaaController2_0_0.<clinit>(App.java:51)
	at com.exp.App.testV2(App.java:37)
	at com.exp.App.main(App.java:23)
	Suppressed: java.lang.UnsatisfiedLinkError: 动态链接库(DLL)初始化例程失败。

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:213)
		... 7 more
	Suppressed: java.lang.UnsatisfiedLinkError: 动态链接库(DLL)初始化例程失败。

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:226)
		... 7 more
	Suppressed: java.io.IOException: Native library (win32-x86-64/D:\Programs\Gogs\MAA\demo\lib\2.0.0\MaaFramework.dll) not found in resource path (D:\Programs\Gogs\MAA\demo\target\classes;D:\Tools\MavenRepository\net\java\dev\jna\jna\5.15.0\jna-5.15.0.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1141)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:297)
		... 7 more

Process finished with exit code 1

```

**Comment by hanhuoer** [comment]
> 来点 java 详细报错

补一下报错截图，刚一直上传失败。

![Snipaste_2024-09-23_17-48-26 2](https://github.com/user-attachments/assets/7da57984-5c40-4938-bddf-92e34de4ffba)

**Comment by hanhuoer** [comment]
目前 `2.0` 系列的测试情况：

|操作系统 | CPU       | 备注 |
| ----------- | ----------- | ----------- |
| Win10 | i7      | 动态链接加载失败，安装了最新的 Microsoft Visual C++ Redistributable Version      |
| Win11 | i7      | 动态链接加载失败，安装了最新的 Microsoft Visual C++ Redistributable Version      |
| MacOS | M2      | 正常加载       |

**Comment by MistEO** [comment]
https://aka.ms/vs/17/release/vc_redist.x64.exe 装的和这个是一个东西吗？

**Comment by hanhuoer** [comment]
> https://aka.ms/vs/17/release/vc_redist.x64.exe 装的和这个是一个东西吗？

是的，我用你新给的链接试了下，打开会让我修复/卸载。

刚点完修复，重启电脑后录了两段视频，可以看看效果，这是在同一台机器上录制的视频。

<img width="638" alt="image" src="https://github.com/user-attachments/assets/d98d9002-ab98-49f7-b9d6-9509482832d9">


### v2.0.0 加载失败视频

https://github.com/user-attachments/assets/cf52382b-5baf-4a57-8290-66d019896900

### v1.8.9 加载成功视频

https://github.com/user-attachments/assets/b4580130-4426-4aa7-b031-cd81af12eefb

**Comment by MistEO** [comment]
试一下 Release 包里的 MaaPiCli.exe，你能正常打开吗？如果能应该就不是依赖问题了

**Comment by hanhuoer** [comment]
> 试一下 Release 包里的 MaaPiCli.exe，你能正常打开吗？如果能应该就不是依赖问题了

如图，可以正常打开。

1.8.9 和 2.0.0 都可以正常打开，效果是下图一样的。

现在不同的就是升级后，这边也只是做了本地库版本的替换和接口调整的工作，然后就...所以很奇怪。

<img width="963" alt="image" src="https://github.com/user-attachments/assets/b134d2b6-f112-4651-a5a8-fcfd926cd7fd">

**Comment by MistEO** [comment]
比较奇怪，能打开这个就确定不是依赖问题了，不用再试 vc_redist 了

你试试 alpha.2 版本能不能打开呢，后面改过一个参数压栈方式，不知道有没有影响

**Comment by hanhuoer** [comment]
> 比较奇怪，能打开这个就确定不是依赖问题了，不用再试 vc_redist 了
> 
> 你试试 alpha.2 版本能不能加载 dll 呢，后面改过一个参数压栈方式，不知道有没有影响

---

这个版本也是一样的问题，我录制了一个视频，里面用了 4 种方式来加载本地库文件，都没有成功。

`2.0` 与 `1.0` 相比，是有什么特别的新增/改动吗，从 `2.0` 开始的各个版本就不能像 `1.0` 那样丝滑接入了。

https://github.com/user-attachments/assets/79651eec-c779-477a-aa3c-80acfb596b4a

**Comment by MistEO** [comment]
可能有的就是 MaaDeps 更新了一下，一些依赖库升级了版本 https://github.com/MaaXYZ/MaaDeps

**Comment by TanyaShue** [comment]
有个玄学的方法可以试一下,在导包的时候试着在所有包最上面import maa.library,大概是叫这个,python使用这个方法能解决,

**Comment by TanyaShue** [comment]
> > 比较奇怪，能打开这个就确定不是依赖问题了，不用再试 vc_redist 了
> > 你试试 alpha.2 版本能不能加载 dll 呢，后面改过一个参数压栈方式，不知道有没有影响
> 
> 这个版本也是一样的问题，我录制了一个视频，里面用了 4 种方式来加载本地库文件，都没有成功。
> 
> `2.0` 与 `1.0` 相比，是有什么特别的新增/改动吗，从 `2.0` 开始的各个版本就不能像 `1.0` 那样丝滑接入了。
> 
>  maa2.0.0-alpha.2.mp4

有个玄学的方法可以试一下,在导包的时候试着在所有包最上面import maa.library,大概是叫这个(java的maafw没怎么用过),python使用这个方法能解决,

**Comment by hanhuoer** [comment]
> > > 比较奇怪，能打开这个就确定不是依赖问题了，不用再试 vc_redist 了
> > > 你试试 alpha.2 版本能不能加载 dll 呢，后面改过一个参数压栈方式，不知道有没有影响
> > 
> > 
> > 这个版本也是一样的问题，我录制了一个视频，里面用了 4 种方式来加载本地库文件，都没有成功。
> > `2.0` 与 `1.0` 相比，是有什么特别的新增/改动吗，从 `2.0` 开始的各个版本就不能像 `1.0` 那样丝滑接入了。
> > maa2.0.0-alpha.2.mp4
> 
> 有个玄学的方法可以试一下,在导包的时候试着在所有包最上面import maa.library,大概是叫这个(java的maafw没怎么用过),python使用这个方法能解决,

---

谢谢你的回复，看了一下，你说的这个 import maa.library 好像为了加载本地库。

其实本篇 issue 就是为了加载(*.dll)，可是加载不起来。

**Comment by TanyaShue** [comment]
是的,maafw似乎在import时有进行一些初始化(会输出如:MaaFw version: v2.0.1),已知的情况是在python中,当maafw位于pyside6后初始化会出现信息: Loading failed with message: 动态链接库(DLL)初始化例程失败。

**Comment by TanyaShue** [comment]
或许可以试一下这种玄学的方法,在main方法的最上面导入import maa.library,即程序运行时最优先导入(即便并没什么作用

**Comment by dongwlin** [comment]
> 是的,maafw似乎在import时有进行一些初始化(会输出如:MaaFw version: v2.0.1),已知的情况是在python中,当maafw位于pyside6后初始化会出现信息: Loading failed with message: 动态链接库(DLL)初始化例程失败。
> 

看看具体的截图

**Comment by TanyaShue** [comment]
![image](https://github.com/user-attachments/assets/f9307b74-0ed8-4aa2-8a28-b7075e2c0316)

**Comment by TanyaShue** [comment]
![image](https://github.com/user-attachments/assets/10fd45af-d1d4-4f24-bf8b-9bf0c2ceb745)

**Comment by TanyaShue** [comment]
> > 是的,maafw似乎在import时有进行一些初始化(会输出如:MaaFw version: v2.0.1),已知的情况是在python中,当maafw位于pyside6后初始化会出现信息: Loading failed with message: 动态链接库(DLL)初始化例程失败。
> 
> 看看具体的截图

调换一下导入顺序就行

**Comment by TanyaShue** [comment]
from PySide6.QtWidgets import QApplication
from maa.library import Library

代码缩减一下就这两行代码就行,这样就没办法运行,调换顺序就能运行

**Comment by hanhuoer** [comment]
> 或许可以试一下这种玄学的方法,在main方法的最上面导入import maa.library,即程序运行时最优先导入(即便并没什么作用

---

我想，你是不是在说 maafw 的本地库有加载顺序的考虑，可能需要手动调整。

刚去试了下，只有 DirectML.dll 是可以顺利加载的。

![image](https://github.com/user-attachments/assets/6950185d-51e1-49de-9355-2801095b77af)

**Comment by moomiji** [comment]
检查JDK目录下是否已经包含，及其文件版本是否小于 14.40
- msvcp140.dll
- vcruntime.dll

如果满足上述条件请考虑将其移除，或尝试在 maaframework.dll 所在目录补齐 14.40 版本的这两个 dll

**Comment by hanhuoer** [comment]
> 检查JDK目录下是否已经包含，及其文件版本是否小于 14.40
> 
> * msvcp140.dll
> * vcruntime.dll
> 
> 如果满足上述条件请考虑将其移除，或尝试在 maaframework.dll 所在目录补齐 14.40 版本的这两个 dll

---

这俩 dll 是随 jdk 下载解压出来的，我去找高于 14.40 的版本试一下。

- msvcp140.dll v14.16.27012.6

- vcruntime140.dll v14.16.27012.6

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/f0b07ff9-4ad1-458e-bbfa-c2bffd09bf0b">

---

> 可能有的就是 [MaaDeps](https://github.com/MaaXYZ/MaaDeps) 更新了一下，一些依赖库升级了版本，之前用的是 2.5.0，现在是 2.6.2

还正准备捣鼓捣鼓，用这个依赖编译一版 2.0 的试试呢。

**Comment by hanhuoer** [comment]
> 检查JDK目录下是否已经包含，及其文件版本是否小于 14.40
> 
> * msvcp140.dll
> * vcruntime.dll
> 
> 如果满足上述条件请考虑将其移除，或尝试在 maaframework.dll 所在目录补齐 14.40 版本的这两个 dll

---

哈哈，终于解决了。

从 `C:\Windows\System32` 拷贝了一版过来，终于加载成功了，是 `v14.40.33810.0`。

非常感谢各位大佬的帮助。

![image](https://github.com/user-attachments/assets/abd2398b-4484-4cc4-941d-ffe49dffd51c)

**Comment by weinibuliu** [comment]
#641
