### ISSUE TITLE
尝试在使用网络桥接模式的MuMu12模拟器上运行任务时会直接闪退

### ISSUE THREAD

**Issue by Starseeker-H** [MaaXYZ/MaaFramework#363]
直接套模板项目的MaaPiCli测试的，后来尝试用Python启动MaaPiCli也是一样的现象

自动寻找adb可以正常找到桥接模式下的模拟器，但Run tasks会直接闪退,

nat模式下的模拟器可以正常运行任务，bridge1和2分别是桥接虚拟网卡和无线网卡的日志（虽然现象上并没有差别）

[maa_nat.log](https://github.com/user-attachments/files/17152709/maa_nat.log)
[maa_bridge1.log](https://github.com/user-attachments/files/17152712/maa_bridge1.log)
[maa_bridge2.log](https://github.com/user-attachments/files/17152714/maa_bridge2.log)

**Comment by MistEO** [comment]
workaround: https://github.com/MaaXYZ/MaaFramework/issues/349#issuecomment-2357519348

**Comment by MistEO** [comment]
RawByNetcat 要起个 server，局域网中好像要管理员权限，也可以试试看

**Comment by MistEO** [comment]
RawByNetcat 这种方法原本就只在部分模拟器上可用，现在有了 EmulatorExtras 这种上位替代，感觉可以把 RawByNetcat 突突了（
