### ISSUE TITLE
能否为context.run_recognition添加明确的成功状态反馈

### ISSUE THREAD

**Issue by TanyaShue** [MaaXYZ/MaaFramework#370]
目前我主要使用Python进行集成。
在2.0.x版本中，获取任务是否匹配成功的过程不够直观，现阶段只能通过解析RecognitionDetail来获取结果。希望能够增加一个类似于context.run_pipeline返回值中completed参数的布尔值，直接表明识别任务是否匹配成功

**Comment by MistEO** [comment]
run_recognition？返回值中的 box 不为 None 就是命中

**Comment by TanyaShue** [comment]
我一直在从各种result中找结果😭
