### ISSUE TITLE
MaaPiCli.exe可以调用python内自定义Action/Recognition吗？

### ISSUE THREAD

**Issue by Elizaaaaa** [MaaXYZ/MaaFramework#375]
大佬好，我在[MaaFramework/sample/python/adb.py](https://github.com/Elizaaaaa/MaaFramework/blob/main/sample/python/adb.py)内编写了自定义任务，测试时使用`python adb.py`可以正确跑pipeline
现在我想把程序打包分享，参考MaaPracticeBoilerplate模板生成install/MaaPiCli.exe后，运行提示找不到我的自定义任务：

[2024-10-02 18:43:49.426][ERR][Px14364][Tx47724][CustomRecognition.cpp][L33][MaaNS::TaskNS::CustomRecognition::analyze] recognition is null [name_=StartWabao] [param_.name=RunKaishi]
RunKaishi使用的CustomRecognition定义在[这里](https://github.com/Elizaaaaa/MaaFramework/blob/main/sample/python/wabaoAction.py#L12)

求问可以指一下python自定义任务的打包范例吗？感谢

**Comment by dongwlin** [comment]
虽然我不明白你为什么要在framework仓库里写你的程序。如果你需要给picli注册act或rec，应该看看toolkit里的pi_register_custom_xxx方法。

**Comment by dongwlin** [comment]
但模板仓库里的那份picli是用的预先编译好的二进制文件，你没有办法注册任何act和rec。如果你需要用picli来注册act或rec的话，应该用toolkit里的pi_run_cli方法来启动一个picli。

**Comment by dongwlin** [comment]
但我感觉你应该是需要 [PyInstaller](https://pyinstaller.org/en/stable/)

**Comment by MistEO** [comment]
同样的题外话，你可以试试基于 [项目模板](https://github.com/MaaXYZ/MaaPracticeBoilerplate) 仓库来写，里面很多东西是现成的。不需要 MaaPiCli.exe 删掉就好了，再自己加一个启动的 py 文件进去

**Comment by Elizaaaaa** [comment]
谢谢两位佬，我研究一下
