### ISSUE TITLE
正则相关：使用OCR时，expected为"0(*)7"时运行到此处会崩溃

### ISSUE THREAD

**Issue by Windsland52** [MaaXYZ/MaaFramework#387]
```json

"七日签到": {
        "recognition": "OCR",
        "expected": "0(*)7",
        "roi": [
            416,
            667,
            35,
            23
        ],
        "only_rec": true,
        "next": [
            "点击七日签到"
        ]
    }

```
cli运行界面：
![屏幕截图 2024-10-13 004605](https://github.com/user-attachments/assets/9ce675fa-c2c6-4ca9-a4f2-841081e9823e)
vscode插件报错：
![QQ图片20241013004625](https://github.com/user-attachments/assets/278bc470-94d5-4fbe-a43c-ff4c8090eadd)
log：
[maa.log](https://github.com/user-attachments/files/17350786/maa.log)

**Comment by Windsland52** [comment]
似乎是错误使用正则导致的问题。

< 星号 * 在正则表达式中是一个特殊字符，它表示“前面的元素可以出现零次或多次”。但是，由于星号前面没有有效的表达式或字符，它不会按预期工作

经测试 7*7（经测试这里*匹配任意字符）、7(.)7（.匹配单个任意字符）、7(.*)7（.*匹配任意长度字符）均可正常运行、匹配。
7(*)7稳定崩溃

**Comment by MistEO** [comment]
直接原因是正则写的有问题。不过崩溃本身是不对的，后面的版本想办法加个检查，最好在加载资源的时候就报错
