### ISSUE TITLE
Can this be used in MMO?

### ISSUE THREAD

**Issue by thelege2nd** [MaaXYZ/MaaFramework#397]
Hello, can this framework be used for other MMO or is it developed just for a specific game? Sorry I don't understand Chinese but seems u guys did something fantastic here. Just wanted to know, Does it have a GUI already for most of its features?

**Comment by MistEO** [comment]
This is a general framework that theoretically applies to all software or games.

**Comment by thelege2nd** [comment]
Does it have a GUI?

**Comment by MistEO** [comment]
As an API, we do not provide a GUI.

However, you can try the GUI contributed by other developers, such as [MFA](https://github.com/SweetSmellFox/MFAWPF) (but it is in Chinese)

**Comment by thelege2nd** [comment]
awesome thanks you
