### ISSUE TITLE
M9A在使用无线ADB连接真安卓机器的时候闪退

### ISSUE THREAD

**Issue by bzyyt** [MaaXYZ/MaaFramework#406]
使用M9A版本1.8.6，winx86，无线ADB连接真机，以及确保安卓端开启了无线调试，开启了允许模拟点击，执行了电脑与设备之间的配对，在电脑端执行adb devices指令可以显示安卓设备，安卓端已经将分辨率调至16：9（2560*1440），配置文件如下：
{
    "adb": {
        "adb_path": "./platform-tools/adb.exe",
        "address": "192.168.2.206:38999",
        "config": {
        }
    },
    "controller": {
        "name": "ADB 默认方式",
        "type": "Adb"
    },
    "resource": "官服",
    "task": [
        {
            "name": "启动游戏",
            "option": [
            ]
        },
        {
            "name": "局外演绎：黄昏的音序",
            "option": [
            ]
        }
    ],
    "win32": {
        "_placeholder": 0
    }
}

情况：在选择run task之后约几秒钟整个终端闪退

log：
[maa.log](https://github.com/user-attachments/files/16550276/maa.log)

![安卓设备的截图](https://github.com/user-attachments/assets/1464b5ba-71bd-4a9c-99d2-ab260f2c0282)

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/commit/cf441aa78bb2b472cb742e23ede9789ae8122064
