### ISSUE TITLE
mumu12使用网络桥接模式时，运行run task闪退

### ISSUE THREAD

**Issue by Starseeker-H** [MaaXYZ/MaaFramework#407]
猜测和 MaaXYZ/MaaFramework#406 原因类似
![image](https://github.com/user-attachments/assets/ec54a75e-5e0f-4f73-bedc-16f07851eabc)
[maa.log](https://github.com/user-attachments/files/16738013/maa.log)
[maa.bak.log](https://github.com/user-attachments/files/16738014/maa.bak.log)

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/commit/cf441aa78bb2b472cb742e23ede9789ae8122064
