### ISSUE TITLE
interface.json里带option的任务怎么写啊

### ISSUE THREAD

**Issue by Stickboy210** [MaaXYZ/MaaFramework#411]
萌新不知道怎么写带选项和参数的task

**Comment by Windsland52** [comment]
可以参考sample和别的项目

**Comment by dongwlin** [comment]
https://github.com/MaaXYZ/MaaFramework/blob/main/tools/interface.schema.json

**Comment by Windsland52** [comment]
> https://github.com/MaaXYZ/MaaFramework/blob/main/tools/interface.schema.json

这个够全

**Comment by Stickboy210** [comment]
感谢！
