### ISSUE TITLE
FeatureMatch中的绿色掩码的功能疑问

### ISSUE THREAD

**Issue by Stickboy210** [MaaXYZ/MaaFramework#412]
FeatureMatch中的绿色掩码功能是需要自己对图像进行涂绿操作吗，还是自动对roi之外的图像进行涂绿后再识别？有时候识图还是会识别出远超出roi的识别框，然后点到roi外的位置，这个是识别算法的bug吗

**Comment by Stickboy210** [comment]
好的，麻烦大佬
[Uploading IssuePack.zip…]()

**Comment by Stickboy210** [comment]
啊嘞

**Comment by Stickboy210** [comment]
[IssuePack.zip](https://github.com/user-attachments/files/17720370/IssuePack.zip)
这回呢

**Comment by Windsland52** [comment]
> [IssuePack.zip](https://github.com/user-attachments/files/17720370/IssuePack.zip) 这回呢

对了

**Comment by MistEO** [comment]
先说结论，你的模板图片有问题，导致算法计算透视出错了。 maafw 的透视算法是要修改的，去保证识别结果不会出 ROI，但是改完后你这张图片仍然不会有识别结果。

模板图片四周你不应该把它涂成黑色，maafw 并不理解”黑色“，原图得长这样才能匹配上

![识别原图 - Copy](https://github.com/user-attachments/assets/26ffdfc9-9d98-45f3-946e-5c1ef36c310d)

你的模板图片只需要像下面这样就行，特征匹配对背景的宽容度是很高的
<img width="40" alt="Bot12" src="https://github.com/user-attachments/assets/781bffbb-4154-4b9d-bc88-c58d2d636bb3">

如果实在不放心你就把背景涂绿（0, 255, 0）然后开启 green_mask

<img width="28" alt="Bot12" src="https://github.com/user-attachments/assets/eb291357-0c84-4572-bd5b-09c307c9ec7f">

这两种做法都是可以正确匹配的

![HomePageBot_300000001_2024 11 14-14 39 42 9074676](https://github.com/user-attachments/assets/1089dd0b-004a-4125-af33-e603dd6d38f4)
![HomePageBot_300000001_2024 11 14-14 39 42 9998830](https://github.com/user-attachments/assets/179bdacc-e029-490e-86fa-5bd3e6230896)

**Comment by Stickboy210** [comment]
原来如此，谢谢大佬！
是我对绿色掩码理解错了

**Comment by Stickboy210** [comment]
我去试试

**Comment by Stickboy210** [comment]
貌似还是不行？什么情况下会触发这个bug？
![识别图片](https://github.com/user-attachments/assets/d5b01154-66b9-40eb-b2e6-f8a562d3bfcd)

**Comment by Stickboy210** [comment]
是因为模板的图片太大了吗（）

**Comment by MistEO** [comment]
你调一调 count 和 ratio，这俩相当于阈值了

**Comment by Stickboy210** [comment]
OK

**Comment by Stickboy210** [comment]
也就是ratio会让成框更简单或者容易吗

**Comment by Stickboy210** [comment]
好的
