### ISSUE TITLE
执行CustomAction时出现 runner id not found错误

### ISSUE THREAD

**Issue by TanyaShue** [MaaXYZ/MaaFramework#413]
每当执行CustomAction时出现 runner id not found错误,在2.0.2版本并没这个问题
当从2.0.2升级到2.2.0版本后出现,
这个bug并不影响CustomAction的运行,但是会出现这个log

[maa.log](https://github.com/user-attachments/files/17760657/maa.log)  

具体测试代码  

![image](https://github.com/user-attachments/assets/162893df-c14c-4099-bbd7-b872043fcb59)  

输出报错  
![image](https://github.com/user-attachments/assets/c675fecc-789c-41ab-9cf9-cd180b363175)

**Comment by weinibuliu** [comment]
记录下日志的是这部分代码 https://github.com/MaaXYZ/MaaFramework/blob/16958ae6c793c69d13d5336ad478e4bde0d36dd3/source/MaaFramework/Tasker/Tasker.cpp#L253-L261
然而我没看懂是什么意思（
但可以确定的是并非全部 Custom Action 都会引发 runner id not found 的错误。
