### ISSUE TITLE
打开MaaPiCli，显示"此应用无法在你的电脑上运行”

### ISSUE THREAD

**Issue by 2236863943-name** [MaaXYZ/MaaFramework#416]
![图片1](https://github.com/user-attachments/assets/e727d207-9f20-49c8-bfe0-5b550f947901)

**Comment by Windsland52** [comment]
> 对于绝大部分用户，请下载 win-x86_64，
若确定自己的电脑是 arm 架构，请下载 win-aarch64
是不是下成了aarch
