### ISSUE TITLE
[feature request] 允许在context run recognition中设置重试次数

### ISSUE THREAD

**Issue by dongwlin** [MaaXYZ/MaaFramework#418]
例如我想实现一个custom recognition，流程是先进行一次模板匹配，若匹配成功，则进一步执行OCR识别。我希望只尝试一次模板匹配，如果失败就直接返回false。但目前的情况是，如果模板匹配没有命中就会进行重试，导致这个recognition需要很长一段时间才能结束。

我认为，这一功能若能实现，可以更加优雅地实现各种recognition的组合。

**Comment by MistEO** [comment]
run_recognition 本来就只跑一次啊？run_pipeline 才会循环跑

**Comment by dongwlin** [comment]
🌿，原来是外面的post pipeline在重试，那没事了（

X﹏X，太笨比了😭
