### ISSUE TITLE
FeatureMatch的template支持接口定义吗

### ISSUE THREAD

**Issue by Stickboy210** [MaaXYZ/MaaFramework#426]
在interface里定义了template后会报错
[maa.log](https://github.com/user-attachments/files/17893851/maa.log)
[interface.json](https://github.com/user-attachments/files/17893857/interface.json)
[DMBot.json](https://github.com/user-attachments/files/17893858/DMBot.json)

**Comment by MistEO** [comment]
确实没支持，下个版本改一下

你可以先在 pipeline 里随便填个图片，反正 interface 里会覆盖掉

**Comment by Stickboy210** [comment]
OK，谢谢大佬，所以说是会覆盖但是如果pipeline里不写就会报错是吧

**Comment by MistEO** [comment]
> OK，谢谢大佬，所以说是会覆盖但是如果pipeline里不写就会报错是吧

是的
