### ISSUE TITLE
关于 `interface.json` 中 `default_case` 用法的疑问 

### ISSUE THREAD

**Issue by Windsland52** [MaaXYZ/MaaFramework#429]
使用该属性时，cli在执行时直接跳过这个选项选择default。
个人认为，如果不需要这个选这个选项，但是要override，直接在task那里就能完成。

该字段出现在 [interface.schema.json](https://github.com/MaaXYZ/MaaFramework/commits/main/tools/interface.schema.json) 的最早提交在 f21672db2b1a9a6c74ccb3b6fee98c77553fcb7f

**Comment by MistEO** [comment]
这个一开始的设计是第一次添加的时候不用选，但是后面 edit 可以改。后面好像做了一半（

**Comment by Windsland52** [comment]
明白哩

**Comment by neko-para** [comment]
我个人倒是觉得目前的设计是ok的吧，default_case相当于提示前端可以使用这个case作为创建任务时选项的默认值，比如下拉框什么的

**Comment by Windsland52** [comment]
> 我个人倒是觉得目前的设计是ok的吧，default_case相当于提示前端可以使用这个case作为创建任务时选项的默认值，比如下拉框什么的

主要是这个东西目前对MaaPiCli来说没什么用，cli目前没有修改任务的功能，使用后想要修改选项值的话还要到maa_pi_config里改

**Comment by neko-para** [comment]
> 主要是这个东西目前对MaaPiCli来说没什么用，cli目前没有修改任务的功能，使用后想要修改选项值的话还要到maa_pi_config里改

是，但是vsc插件，MAAWPF之类的就可以用（

**Comment by Windsland52** [comment]
> > 主要是这个东西目前对MaaPiCli来说没什么用，cli目前没有修改任务的功能，使用后想要修改选项值的话还要到maa_pi_config里改
> 
> 是，但是vsc插件，MAAWPF之类的就可以用（

插件我早上试看还是要选的（还是说新版本可以了？），MFAWPF的话我之前提过加默认值，但是很久没动静，所以目前也是没用上，目前实现默认值的方式是调选项顺序。
最重要的是会导致cli功能受影响，除非分别给cli和wpf打包。

**Comment by Windsland52** [comment]
> > > 主要是这个东西目前对MaaPiCli来说没什么用，cli目前没有修改任务的功能，使用后想要修改选项值的话还要到maa_pi_config里改
> > 
> > 
> > 是，但是vsc插件，MAAWPF之类的就可以用（
> 
> 插件我早上试看还是要选的（还是说新版本可以了？），MFAWPF的话我之前提过加默认值，但是很久没动静，所以目前也是没用上，目前实现默认值的方式是调选项顺序。 最重要的是会导致cli功能受影响，除非分别给cli和wpf打包，在ci install的时候给cli版本去掉 default case。

**Comment by neko-para** [comment]
插件会在你config里面缺失配置时优先使用default_case而不是cases[0]
以及最近插件在重置中，引入了一个新的web界面提供配置能力，里面的配置项的下拉框的预设值就是使用的default_case

**Comment by Windsland52** [comment]
明白哩
