### ISSUE TITLE
pyinstaller打包的.py程序运行不了

### ISSUE THREAD

**Issue by Stickboy210** [MaaXYZ/MaaFramework#440]
自己集成的程序运行时报错：Traceback (most recent call last):
  File "__main__.py", line 682, in <module>
    main()
  File "__main__.py", line 543, in main
    Toolkit.init_option(user_path)
  File "maa\toolkit.py", line 36, in init_option
  File "maa\toolkit.py", line 193, in _set_api_properties
RuntimeError: Library not initialized, please call `library.open()` first.
[PYI-16004:ERROR] Failed to execute script '__main__' due to unhandled exception!
但是.py文件是可以正常运行的，打包的.exe文件运行后就会有上面的报错，是有什么依赖项没有添加进来吗

**Comment by Stickboy210** [comment]
[__main__.zip](https://github.com/user-attachments/files/17987821/__main__.zip)
这个是.py文件

**Comment by TanyaShue** [comment]
可能是[这个](https://github.com/MaaXYZ/MaaFramework/issues/361)原因,可以看一下python环境中的vcruntime和msvcp140的版本

**Comment by MistEO** [comment]
https://github.com/bamboo98/ZenlessZoneZero-Copilot/blob/main/build.py 参考这个打包脚本试试呢？直接打包的好像没有 bin 文件

**Comment by Stickboy210** [comment]
谢谢大佬，我看一下

**Comment by Stickboy210** [comment]
用了build.py打包程序后好像变成这种报错了：动态链接库(DLL)初始化例程失败
然后还有这个报错：
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\Users\24715\AppData\Local\Temp\_MEI142922\maa\bin\MaaFramework.dll'. Most likely this dynlib/dll was not found when the application was frozen.
并且我去找了这个文件夹，没有这个文件夹，是不是打包程序找错了（）打包时需要添加这个路径到运行参数中吗

**Comment by MistEO** [comment]
site_packages_paths 自己改一下

**Comment by Stickboy210** [comment]
_MEI90202
_MEI175442
有两个文件夹，应该用哪个里的文件？

**Comment by MistEO** [comment]
你的 python 咋装的，怎么会在这个 temp 文件夹里？

**Comment by Stickboy210** [comment]
我不知道啊（）

**Comment by MistEO** [comment]
这个 build.py 本身就是打包脚本，你直接用运行就好了，不是要用 pyinstaller 打包 build.py（怀疑你是这么操作的？

**Comment by Stickboy210** [comment]
没有啊，我运行的就是build.py，名字改成要打包的文件

**Comment by MistEO** [comment]
不知道你的环境什么情况，正常这里的路径应该是 `C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\maa\bin\MaaFramework.dll` 这样的

这个 Temp_MEI 我查了下是 pyinstaller 打包用的临时文件夹，但是还没到打包那一步，怎么会定位过去呢

**Comment by Stickboy210** [comment]
哦哦，因为我这个是运行打包好的程序的报错，打包是能正常打包的

**Comment by Stickboy210** [comment]
但是打包的程序运行就会报这个错，我试过更新过msvcp140.dll、vcruntime.dll这两个dll文件，没有什么帮助

**Comment by TanyaShue** [comment]
将这两个dll复制替换Python环境根目录下的dll就行，虚拟环境就替换虚拟环境下Python根目录里的dll，再打包就行

**Comment by Stickboy210** [comment]
集成之后运行程序，还是会有这样的报错：
Traceback (most recent call last):
  File "__main__.py", line 720, in <module>
  File "__main__.py", line 577, in main
  File "maa\toolkit.py", line 36, in init_option
  File "maa\toolkit.py", line 193, in _set_api_properties
RuntimeError: Library not initialized, please call `library.open()` first.
[PYI-9520:ERROR] Failed to execute script '__main__' due to unhandled exception!
这是我的代码里有什么问题导致的吗

**Comment by MistEO** [comment]
试一下最新的 beta 版本，看看报什么错，2.3.0b2

**Comment by Stickboy210** [comment]
如果用build.py来打包，程序运行会报错：
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 379, in __init__
FileNotFoundError: Could not find module 'None' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "maa\__init__.py", line 8, in <module>
  File "maa\library.py", line 36, in open
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'None'. Most likely this dynlib/dll was not found when the application was frozen.
[PYI-6988:ERROR] Failed to execute script '__main__' due to unhandled exception!
如果直接用pyinstaller打包后，程序运行时会报错：
Traceback (most recent call last):
  File "__main__.py", line 733, in <module>
  File "__main__.py", line 586, in main
  File "maa\toolkit.py", line 36, in init_option
  File "maa\toolkit.py", line 193, in _set_api_properties
RuntimeError: Library not initialized, please call `library.open()` first.
[PYI-30968:ERROR] Failed to execute script '__main__' due to unhandled exception!

**Comment by MistEO** [comment]
那和vcruntime和msvcp140的版本没有关系（不排除这俩版本也可能有问题，但现在还没到那一步，目前出的问题在这之前）

**Comment by MistEO** [comment]
> 如果直接用pyinstaller打包后，程序运行时会报错：
> RuntimeError: Library not initialized, please call library.open() first.

这里是有问题的，这个报错 2.3.0b2 我们已经从代码里删掉了，无论如何都不应该有的。
结合上面 build.py 的报错，我感觉还是有 python 环境及版本有关系，但具体原因暂时不知道

**Comment by TanyaShue** [comment]
![image](https://github.com/user-attachments/assets/b60fd9ac-8f4a-4756-be81-fd79b47b2de4)
![image](https://github.com/user-attachments/assets/16a71e99-990c-450a-bbf7-452a39b8d2fb)


确保python环境中msvcp140.dll、vcruntime140.dll这两个版本大于14.40,之后,再试一下build.py,我之前也是这个报错,我替换后就解决了,没找到msvcp140.dll、vcruntime140.dll对应的版本可以去windows目录下复制一个,一般位于C:\Windows\System32目录下就有,python环境中默认版本一般是14.38

**Comment by TanyaShue** [comment]
![image](https://github.com/user-attachments/assets/409173f3-671f-41ae-a3a0-026761463065)
windows目录下的好像更新到14.42了,不确定能不能行,不行的话去[这里](https://github.com/TanyaShue/MaaYYs/tree/master/DLL)复制一下也行

**Comment by Stickboy210** [comment]
> > 如果直接用pyinstaller打包后，程序运行时会报错：
> > RuntimeError: Library not initialized, please call library.open() first.
> 
> 这里是有问题的，这个报错 2.3.0b2 我们已经从代码里删掉了，无论如何都不应该有的。 结合上面 build.py 的报错，我感觉还是有 python 环境及版本有关系，但具体原因暂时不知道

请问更新2.3.0b2直接替换掉deps里的文件可以吗，需要其他操作吗

**Comment by Stickboy210** [comment]
我看环境里还是2.2.2的版本

**Comment by MistEO** [comment]
> > > 如果直接用pyinstaller打包后，程序运行时会报错：
> > > RuntimeError: Library not initialized, please call library.open() first.
> > 
> > 
> > 这里是有问题的，这个报错 2.3.0b2 我们已经从代码里删掉了，无论如何都不应该有的。 结合上面 build.py 的报错，我感觉还是有 python 环境及版本有关系，但具体原因暂时不知道
> 
> 请问更新2.3.0b2直接替换掉deps里的文件可以吗，需要其他操作吗

pip install --upgrade maafw==2.3.0b2

**Comment by Stickboy210** [comment]
OKOK

**Comment by TanyaShue** [comment]
![image](https://github.com/user-attachments/assets/dc4b2d93-d7ce-4131-8869-5937c2a6ff1b)
我试了一下,可以打包

**Comment by Stickboy210** [comment]
现在直接打包的报错是这个，看起来就是没有bin导致的：
Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "maa\__init__.py", line 12, in <module>
  File "maa\library.py", line 14, in open
FileNotFoundError: `D:\大学记忆\AiGames\MAA\MAADuelinks\install\dist\__main__\_internal\maa\bin` does not exist.
[PYI-21148:ERROR] Failed to execute script '__main__' due to unhandled exception!
然后用build打包报错是这样：
Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "maa\__init__.py", line 12, in <module>
  File "maa\library.py", line 30, in open
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\24715\\AppData\\Local\\Temp\\_MEI150722\\maa\\bin\\MaaFramework.dll'. Most likely this dynlib/dll was not found when the application was frozen.
[PYI-13244:ERROR] Failed to execute script '__main__' due to unhandled exception!
看起来就是没有maaframework.dll的问题

**Comment by TanyaShue** [comment]
可是我好像能打包

**Comment by Stickboy210** [comment]
> ![image](https://private-user-images.githubusercontent.com/152378303/393066668-dc4b2d93-d7ce-4131-8869-5937c2a6ff1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTE2MTQsIm5iZiI6MTczMzQ1MTMxNCwicGF0aCI6Ii8xNTIzNzgzMDMvMzkzMDY2NjY4LWRjNGIyZDkzLWQ3Y2UtNDEzMS04ODY5LTU5MzdjMmE2ZmYxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwMjE1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjEwMTkyOTIzMjEyZDY1ODk2YTg5MGY4MTZiZDRkYWYwNmI2ZmYzN2FkNzg0M2QzODI5OTVjNzMwOThiMWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dOslwM1JvD3J_zjA2MVjziZXrU7Jv3_8h_2-HpQSN_k) 我试了一下,可以打包

竟然真的可以吗，我改一改环境试一下

**Comment by TanyaShue** [comment]
对了,推荐在初始资源的地方也抛个错误,不然没有adb会闪退
![image](https://github.com/user-attachments/assets/79533125-244c-4b7b-a862-349b07ad1d47)

**Comment by Stickboy210** [comment]
> 对了,推荐在初始资源的地方也抛个错误,不然没有adb会闪退 ![image](https://private-user-images.githubusercontent.com/152378303/393072548-79533125-244c-4b7b-a862-349b07ad1d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTMzMzYsIm5iZiI6MTczMzQ1MzAzNiwicGF0aCI6Ii8xNTIzNzgzMDMvMzkzMDcyNTQ4LTc5NTMzMTI1LTI0NGMtNGI3Yi1hODYyLTM0OWIwN2FkMWQ0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwMjQzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDA2YTcxODM3YjhhYTlmNzc1MGUwYzMwMjFjYTU3NjY5N2NkYTM3NGMxYjRjOGM2YWRkNzJmZDI3OWEwNGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.094HH_JQ7EbSfVOrmx5-YYth6VQvQoWY8DfXWPGQwec)

好的：）

**Comment by TanyaShue** [comment]
[Test.zip](https://github.com/user-attachments/files/18032106/Test.zip)
这是打包代码,不行就把里面的DLL替换掉python根目录里的,我试了一下,只要版本大于14.40应该都行

**Comment by Stickboy210** [comment]
我看build.py的日志确实成功找到bin文件夹了，但是打包之后不知道为什么不行

**Comment by Stickboy210** [comment]
我应该已经把替换掉python环境的dll了，还是不行啊:（

**Comment by TanyaShue** [comment]
报错是什么

**Comment by Stickboy210** [comment]
还是之前的那个，pyimod03_ctypes.install..PyInstallerImportError: Failed to load dynlib/dll 'C:\Users\24715\AppData\Local\Temp\_MEI150722\maa\bin\MaaFramework.dll'. Most likely this dynlib/dll was not found when the application was frozen.

**Comment by TanyaShue** [comment]
是打包时报错还是运行时报错

**Comment by Stickboy210** [comment]
运行时，打包时一般都不报错的

**Comment by TanyaShue** [comment]
你用的是虚拟环境?

**Comment by Stickboy210** [comment]
没用虚拟环境

**Comment by TanyaShue** [comment]
本地环境我没试过

**Comment by TanyaShue** [comment]
python本地环境好像没有msvcp140,我也不知道它调用的哪的DLL可能直接调用的系统的或者其他地方的msvcp140,推荐使用Anconda或者minconda之类的

**Comment by Stickboy210** [comment]
OK，那我试试

**Comment by Stickboy210** [comment]
感谢各位大佬

**Comment by Stickboy210** [comment]
用虚拟环境就可以运行了0.0，可能我环境有点问题（），非常感谢各位大佬！
