### ISSUE TITLE
讨论：新增 Action: Override、新增 interrupt with override

### ISSUE THREAD

**Issue by MistEO** [MaaXYZ/MaaFramework#465]
感觉会很有作用，但感觉会向着maa的混沌tasks.json一路狂奔（

@MaaXYZ/application-developers

**Comment by Windsland52** [comment]
这是什么用法，有例子吗

**Comment by dongwlin** [comment]
> 这是什么用法，有例子吗

可以参考interface里的那些option

**Comment by Windsland52** [comment]
> > 这是什么用法，有例子吗
> 
> 可以参考interface里的那些option

那next with override是什么，给没个next task都override吗

**Comment by Windsland52** [comment]
不是很清楚什么时候需要不在interface里override，而在task里override，有什么具体应用吗

**Comment by neko-para** [comment]
> 不是很清楚什么时候需要不在interface里override，而在task里override，有什么具体应用吗

比如一直被问的if和while

**Comment by Windsland52** [comment]
那还挺好的

**Comment by MistEO** [comment]
根据群友的意见，暂时是不做（

**Comment by moomiji** [comment]
不要啊，这个特性还是很好用的

- 相同后续流程但roi东一个西一个

- 相同任务新增 sub
```
{
    "Orange": {
        "recognition": XXX,
        "action": "Click",
        "next": [ "Cat", "Dog" ]
    },
    "Sub_Orange": {
        "action": "Override",
        "interrupt": [ "StartFruit" ]
    }
}
```

**Comment by neko-para** [comment]
> 不要啊，这个特性还是很好用的
> 
> - 相同后续流程但roi东一个西一个
> 
> - 相同任务新增 sub
> ```jsonc
> {
>     "Orange": {
>         "recognition": XXX,
>         "action": "Click",
>         "next": [ "Cat", "Dog" ]
>     },
>     "Sub_Orange": {
>         "action": "Override",
>         "interrupt": [ "StartFruit" ]
>     }
> }
> ```

感觉玛丽想的和你说的不是一回事诶
