### ISSUE TITLE
使用MaaPracticeBoilerplate启动程序后提示bin不存在

### ISSUE THREAD

**Issue by SCzfdf** [MaaXYZ/MaaFramework#468]
已按照md下载依赖到deps文件夹并初始化
python ./install.py

Found existing OCR directory, skipping default OCR model import.
Install to /xxx/install successfully.

下面是运行报错
Traceback (most recent call last):
  File "/Users/cgb/PycharmProjects/randomDice/__main__.py", line 3, in <module>
    from deps.binding.Python.maa.controller import AdbController
  File "/Users/cgb/PycharmProjects/randomDice/deps/binding/Python/maa/__init__.py", line 12, in <module>
    Library.open(__PATH)
  File "/Users/cgb/PycharmProjects/randomDice/deps/binding/Python/maa/library.py", line 14, in open
    raise FileNotFoundError(f"`{path}` does not exist.")
FileNotFoundError: `/xxx/deps/binding/Python/maa/bin` does not exist.

**Comment by MistEO** [comment]
```bash
python -m pip install maafw
```

**Comment by SCzfdf** [comment]
> ```shell
> python -m pip install maafw
> ```

不行. 还是一样的报错. 而且确实没有这个bin文件

**Comment by MistEO** [comment]
你从哪 import 的 maa，看看你的代码

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/blob/main/sample/python/__main__.py

**Comment by SCzfdf** [comment]
> 你从哪 import 的 maa，看看你的代码

不太会py. 是弄了个虚拟环境, 然后在框架教程的基础上执行 python -m pip install maafw

这是现在的目录结构
![image](https://github.com/user-attachments/assets/51bb7d52-c806-4431-a511-891ee9fbed5a)

这是项目路径
https://github.com/SCzfdf/MaaRandomDicePy

**Comment by neko-para** [comment]
别用deps里面的那个python binding, 用你自己pip安装的版本

**Comment by MistEO** [comment]
项目模板是给 MaaPiCli 用的，你自己写 python 代码用不了这个，或者说没法直接用

建议多看文档（

https://github.com/MaaXYZ/MaaFramework/blob/main/docs/zh_cn/1.1-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B.md

![image](https://github.com/user-attachments/assets/204b4144-ca3f-4ee2-a693-079264b756cf)

**Comment by SCzfdf** [comment]
> 别用deps里面的那个python binding, 用你自己pip安装的版本

可以了 谢谢

**Comment by SCzfdf** [comment]
> MaaPracticeBoilerplate 是给 MaaPiCli 用的，你自己写 python 代码用不了这个，或者说没法直接用
> 
> 建议多看文档（
> 
> https://github.com/MaaXYZ/MaaFramework/blob/main/docs/zh_cn/1.1-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B.md
> 
> ![image](https://private-user-images.githubusercontent.com/18511905/396430411-d983de54-2048-4589-8a7a-ebd4749d9211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjY2MjQsIm5iZiI6MTczNDQyNjMyNCwicGF0aCI6Ii8xODUxMTkwNS8zOTY0MzA0MTEtZDk4M2RlNTQtMjA0OC00NTg5LThhN2EtZWJkNDc0OWQ5MjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MmI0NTI4MzE0ZjJkMTE4NWFhNzY2ODA5YTQyNDY5MzdjNjg5YTQ5NGYzNDU4MGU1ZWUyZTExMGE3ZjYxZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L78lr_ZoyZSVTUMSFxKWQgh-h6pSGsLf-LMLm8yk01U)

可以了 谢谢
