### ISSUE TITLE
adb点击位置错误

### ISSUE THREAD

**Issue by MistEO** [MaaXYZ/MaaFramework#471]
我遇到了可能相关的问题, 通过adb不能执行点击(任务用win32连接可以正常执行)
- 目标是: 在模拟器中识别文字"快速更换", 并进行点击
- 问题是: MaaDebugger内显示成功识别了对应文字, 但实际没有执行点击
![image](https://github.com/user-attachments/assets/1e4b4679-89b1-49c5-94af-4f5e38beedd6)
![image](https://github.com/user-attachments/assets/48848969-d671-48df-b49d-bd9bff22f49f)
- 终端显示了一些错误信息
`[2024-12-17 23:14:09.545][ERR][Px22432][Tx34323][UnitBase.cpp][L64][MaaNS::CtrlUnitNs::UnitBase::startup_and_read_pipe] child return error [argv.exec=D:/Software/Nox/bin/nox_adb.exe] [argv.args=["-s","127.0.0.1:62001","shell","dumpsys window displays | grep DisplayFrames | tail -n 1 | grep -o -E [0-9]+"]]
[2024-12-17 23:14:09.545][ERR][Px22432][Tx34323][MtouchHelper.cpp][L60][MaaNS::CtrlUnitNs::MtouchHelper::request_display_info] failed to request resolution`
- 完整的日志
[maa.log](https://github.com/user-attachments/files/18167607/maa.log)
请大佬们也看看, 非常感谢!

_Originally posted by @quarterQ4 in https://github.com/MaaXYZ/MaaFramework/issues/305#issuecomment-2548752787_

**Comment by MistEO** [comment]
Hi @quarterQ4

可以发下你电脑上这个命令的完整输出看下吗

```bash
D:/Software/Nox/bin/nox_adb.exe -s 127.0.0.1:62001 shell dumpsys window displays
```

**Comment by quarterQ4** [comment]
``

> Hi @quarterQ4
> 
> 可以发下你电脑上这个命令的完整输出看下吗
> 
> ```shell
> D:/Software/Nox/bin/nox_adb.exe -s 127.0.0.1:62001 shell dumpsys window displays
> ```
[shell_dumpsys命令输出.txt](https://github.com/user-attachments/files/18205720/shell_dumpsys.txt)
输出是这些

**Comment by MistEO** [comment]
夜神这是什么版本的安卓，感觉有点老了。之后会试着兼容一下

急着用可以先换个模拟器，mumu 或者 雷电都可以，不急就等 maafw 更新吧

**Comment by quarterQ4** [comment]
> 夜神这是什么版本的安卓，感觉有点老了。之后会试着兼容一下
> 
> 急着用可以先换个模拟器，mumu 或者 雷电都可以，不急就等 maafw 更新吧

安卓版本是7, 确实比较老
另外现在interface下指定adb的input为1就可以用, win32接也行

**Comment by MistEO** [comment]
v2.4.0 临时修改了一下判断屏蔽了

等 3.0 再重构一下 https://github.com/MaaXYZ/MaaFramework/issues/478
