### ISSUE TITLE
从 release 包中移除 python binding

### ISSUE THREAD

**Issue by MistEO** [MaaXYZ/MaaFramework#473]
CI 还得改改，先记一下省的忘了

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/commit/fdb9a0c5d67ac7353fe129bf21c883a19761666e

**Comment by moomiji** [comment]
既然 pip 会因为容量不足而删掉，要不改回去，或者发到 MaaXYZ/pkg ?

**Comment by MistEO** [comment]
MaaXYZ/pkg 听起来不错，带带带带
