### ISSUE TITLE
请问下打出来的MaaXXX-android-aarch64-v1.1.0.zip该如何使用

### ISSUE THREAD

**Issue by SCzfdf** [MaaXYZ/MaaFramework#475]
是可以在安卓手机上安装使用? 可是解压也没有apk.

**Comment by MistEO** [comment]
可以在 shell 里本机 adb 连接然后用，用 termux 之类的工具，需要一些奇技淫巧（

是偏极客向的，不太适合普通用户

之后的版本可能会出个 apk 之类的（画大饼

**Comment by SCzfdf** [comment]
> 可以在 shell 里本机 adb 连接然后用，用 termux 之类的工具，需要一些奇技淫巧（
> 
> 是偏极客向的，不太适合普通用户
> 
> 之后的版本可能会出个 apk 之类的（画大饼

好的 期待
