### ISSUE TITLE
动作stoptask会执行前任务的on error

### ISSUE THREAD

**Issue by Saratoga-Official** [MaaXYZ/MaaFramework#499]
经过测试，在pipeline中照如下写会造成这两个任务无限循环，推测是stoptask之后执行了on error
{
    "测试A": {
        "next": [
            "测试B"
        ],
        "post_wait_freezes": 0,
        "interrupt": [],
        "on_error": [
            "测试A"
        ],
        "focus": true,
        "focus_tip": "测试A",
        "focus_tip_color": "Red"
    },
    "测试B": {
        "action": "StopTask",
        "post_wait_freezes": 0,
        "interrupt": [],
        "on_error": [],
        "focus": true,
        "focus_tip": "测试B",
        "focus_tip_color": "Red"
    }
}
使用MFA测试如图
![Z`D~8D}V_WR4LYS$3Q{`}_S](https://github.com/user-attachments/assets/bffd5cc6-6bdc-421d-a8bb-c4f43bf6be53)

**Comment by MistEO** [comment]
log 发一下，debug/maa.log

**Comment by Saratoga-Official** [comment]
[maa.log](https://github.com/user-attachments/files/18247990/maa.log)

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/actions/runs/12498746357?pr=500 帮忙试试这个包好使了不

**Comment by Saratoga-Official** [comment]
咋用

**Comment by Saratoga-Official** [comment]
[maa.log](https://github.com/user-attachments/files/18249253/maa.log)
