### ISSUE TITLE
希望添加 on_error触发 的回调协议

### ISSUE THREAD

**Issue by overflow65537** [MaaXYZ/MaaFramework#504]
#### 如果不添加 on_error 
在timeout后回调协议会发送任务失败信息

#### 添加on_error后
timeout后会等待on_error执行完成,除非on_error执行失败,否则就不会发送任务失败信息

#### 是否可以添加一个on_error触发的信息来表明任务已经失败了

**Comment by MistEO** [comment]
on error 相当于 try catch，catch 兜住了程序自然就不报错了，没 catch 程序就有报错信息了（

需要的话可以自己把 handle 的函数加个 focus
